google/turbinia

- docker/be_worker_builder/README.md
- docker/be_worker_builder/be_reducer.sh
- docker/be_worker_builder/be_wrapper.sh
- docker/be_worker_builder/build/build.sh
- docker/be_worker_builder/build/requirements.txt
- docker/be_worker_builder/run.sh
- docker/redis_builder/Dockerfile
- docker/redis_builder/Dockerfile.run
- docker/redis_builder/build.sh
- docker/third_party/ubuntu-essential/MIT-LICENSE
- docker/third_party/ubuntu-essential/README
- docker/third_party/ubuntu-essential/build_ubuntu_essential.sh
> Initial commit of docker bits to turbinia

- experimental/turbineweb/__init__.py
- experimental/turbineweb/models.py
- experimental/turbineweb/templates/base.html
- experimental/turbineweb/templates/inventory.html
- experimental/turbineweb/templates/item.html
- experimental/turbineweb/views.py
reviewer: @coryaltheide 
ref: #2
> Experimental webui frontend

- README.md
Description lifted from http://www.basistech.com/the-advantages-of-cloud-computing-for-forensic-analysis-an-osdfcon-presentation/
> Add a one-line description of Turbinia

- docker/be_worker_builder/be_wrapper.sh
- turbinia/evidence.py
Just fixing a couple of small typos.
> Fix a couple of typos.

- AUTHORS
Not sure if this was supposed to be alphabetical by first or last name...
> Update Authors list

- turbinia/evidence.py
- turbinia/processors/google_cloud.py
Note:  A lot of this code comes from work from jberggren@ in another repository.  I'm not adding tests here because this code will likely be changed to use a separate library later on.
> Attach/Detach Google Cloud disks with pre/post-processors

- docs/install.md
Move documentation to /docs to make them updatable by external users etc.
> Move documentation from wiki -> /docs

- tools/gcp_init/start-turbinia-common.sh
- tools/gcp_init/start-turbinia-server.sh
- tools/gcp_init/start-turbinia-worker.sh
- tools/gcp_init/start-wrapper.sh
- tools/gcp_init/update-scripts.sh
These are pretty lame, but we can iterate on them.  I created a new issue (https://github.com/google/turbinia/issues/67) to turn them into something decent.
> Add super basic/hacky startup scripts

- turbiniactl
FYI, I still really want to do something like #41, but will just add this for now to keep things moving.
> Add GoogleCloudDisk evidence type to turbiniactl

- turbinia/processors/google_cloud.py
See https://github.com/google/google-api-python-client/issues/299 for details.
> Turn off cache discovery as it stacktraces noisily

- turbinia/evidence.py
- turbinia/processors/google_cloud.py
- turbiniactl
Note this has a diffbase against the gcp-embedded branch in the other PR.
> Add initial support for partitions on raw disks

- turbinia/evidence.py
- turbinia/pubsub.py
- turbinia/state_manager.py
- turbinia/task_manager.py
Unicode forced conversion in the state_manager is to make sure that Datastore stores the correct data type, otherwise we store a Blob and get back a byte array of ordinal ascii chars.   Note that there are still other modules that need to be converted.
> Use unicode_literals and force unicode conversion

- turbiniactl
Also refactored some functions in turbiniactl to separate waiting / getting data / printing.
> Add --wait flag with poll/wait mechanism

- turbinia/config/logger.py
- turbinia/output_writers.py
- turbinia/pubsub.py
- turbinia/workers/__init__.py
- turbiniactl
> Fix up the loggers and eliminate double logging

- turbinia/evidence.py
- turbinia/jobs/__init__.py
- turbinia/jobs/psort.py
- turbinia/workers/__init__.py
- turbinia/workers/psort.py
> Add Psort task

- requirements.txt
> Pin google-cloud-core to 0.26.0

- turbinia/workers/__init__.py
(Also see email sent privately)
> More exception/result checks

- turbinia/config/__init__.py
FYI, I'll get the style/lint/test checks automated through github sometime soon so that we can catch these earlier.
> Fix import typo

- turbinia/evidence.py
- turbinia/processors/mount_local.py
- turbiniactl
Note that this flag is specifically just for mounting.  I have some plans for a more complete implementation to support partitions more generally (right now we just process the full disk as specified to turbiniactl).
> Add --mount_partition flag used by mount_local preprocessor

- turbinia/config/__init__.py
- turbinia/config/turbinia_config.py
- turbinia/workers/plaso.py
- turbinia/workers/psort.py
This will make it a little easier to debug things.
> Add DEBUG_TASKS config var

- turbinia/output_manager.py
> Set chunk_size in GCS Blobs

- turbinia/workers/__init__.py
- turbiniactl
This isn't perfect, but we get better status messages like this.  #115 will help out with getting relevant information back to the client.
> Set better status messages

- requirements.txt
> Update the requiremnts for Turbinia

- requirements.txt
> Pin the version of psq

- turbinia/config/turbinia_config.py
Per #101 and consolidate all the variables (from init scripts) into 1 place.
> Clean up and clarify config file

- tools/gcf_init/deploy_gcf.py
- turbinia/config/__init__.py
- turbinia/config/turbinia_config.py
- turbiniactl
> fix turbinia status by pointing to the correct GCF region

- docs/install.md
- turbinia/config/turbinia_config.py
Regarding Issue #132
The installation doc deserves a major revamp for the sake of legiblity and clear instructions. The formatting and structures have been updated. New steps are added to address missing dependencies when building and installing in the virutalenv and GCP service setup (API, service account, etc).
> Major revamp of install.md doc

- turbiniactl
> Replace another ZONE with TURBINIA_REGION

- turbinia/state_manager.py
> Explicitly set project in client setup

- tests/pubsub.py
Forgot to update when I changed the Kombu class; `testBadCheckMessages` & `testCheckMessages` tests now pass.
> Fix Kombu tests

- turbinia/celery.py
- turbinia/client.py
- turbinia/config/__init__.py
- turbinia/config/turbinia_config.py
- turbinia/config/turbinia_config_test.py
- turbinia/evidence.py
- turbinia/jobs/plaso.py
- turbinia/jobs/psort.py
- turbinia/jobs/worker_stat.py
- turbinia/lib/google_cloud.py
- turbinia/message.py
- turbinia/output_manager.py
- turbinia/output_manager_test.py
- turbinia/processors/google_cloud.py
- turbinia/processors/mount_local.py
- turbinia/pubsub.py
- turbinia/state_manager.py
- turbinia/turbiniactl.py
Fixing some inconsistencies and removing unused imports etc.
> First round of cleanups

- turbinia/evidence.py
- turbinia/message.py
- turbinia/task_manager.py
- turbinia/turbiniactl.py
- turbinia/workers/__init__.py
- turbinia/workers/worker_stat.py
A better way to handle the config data is in  #211, but this will do for now.  More extensive recipe configuration is planned, but it will take more effort as well.
> Add --filter_patterns_file and plumb it through all evidence

- .gitignore
- terraform/gcp/machines.tf
- terraform/gcp/main.tf
- terraform/gcp/startup_scripts/install_server.sh
- terraform/gcp/startup_scripts/install_worker.sh
- terraform/gcp/templates.tf
- terraform/gcp/variables.tf
Use terraform to deploy server and workers. Initial PR, still needs installation scripts.
> Terraform support

- turbinia/lib/libcloudforensics.py
- turbinia/lib/libcloudforensics_test.py
Initial import. We can refactor as needed after this one is merge.
> Initial import of libcloudforensics

- turbinia/config/__init__.py
- turbinia/config/turbinia_config.py
Removing INSTANCE, SCRATCH_PATH, DEVICE_NAME and GCS_MOUNT_DIR.
> Fixup config and remove unneeded vars

- turbinia/client.py
- turbinia/state_manager.py
- turbinia/turbiniactl.py
> Set instance to INSTANCE_ID instead of PUBSUB_TOPIC

- turbinia/workers/__init__.py
- turbinia/workers/workers_test.py
This fixes up the results_check() and how it's used to handle invalid objects, and adds some new tests for the run() and run_wrapper() functions.
> Better result check and tests

- turbinia/output_manager.py
- turbinia/workers/__init__.py
- turbinia/workers/artifact.py
... Also fix result.close() in artifacts.py
> Fix setting of base_output_dir

- test_data/wordpress_access_logs.txt
- turbinia/jobs/__init__.py
- turbinia/jobs/analysis/docker_logs.py
- turbinia/jobs/analysis/http_access_logs.py
- turbinia/workers/analysis/wordpress.py
- turbinia/workers/analysis/wordpress_test.py
- turbinia/workers/artifact.py
This PR adds a couple Workers and analysis modules:
* Docker logs extraction job: Extract logs from Docker containers
* Wordpress analysis worker: Analyze Wordpress web access logs and assess the likelihood of compromise.
> Wordpress & Docker

- turbinia/lib/utils.py
- turbinia/workers/analysis/jenkins.py
>  Set status and fix linting in Jenkins task

- terraform/gcp/machines.tf
- terraform/gcp/variables.tf
Most of the other stuff I had for the terraform config isn't ready for review yet (I had something started that would create a tfvars.json file from the Turbinia config).   This is also untested, :), but I think that's ok since nothing is working yet anyway, and I know you had wanted to work on some of this, so this might be helpful.
> Add enabling of APIs and switch to ubuntu 18.0.4

- turbinia/workers/__init__.py
> Only save evidence info when copyable == True

- turbinia/jobs/__init__.py
- turbinia/jobs/grep.py
- turbinia/jobs/hadoop.py
- turbinia/jobs/http_access_logs.py
- turbinia/jobs/imports_test.py
- turbinia/jobs/interface.py
- turbinia/jobs/jenkins.py
- turbinia/jobs/manager.py
- turbinia/jobs/manager_test.py
- turbinia/jobs/plaso.py
- turbinia/jobs/psort.py
- turbinia/jobs/sshd.py
- turbinia/jobs/strings.py
- turbinia/jobs/tomcat.py
- turbinia/jobs/worker_stat.py
- turbinia/task_manager.py
Second try at https://github.com/google/turbinia/pull/248
> Job manager

- setup.py
Create new release so dfTimewolf can use the latest client updates.
> Bump version to 20181003

- turbinia/evidence.py
... to disambiguate between _preprocess() and preprocess().
> Quick update to evidence docstrings

- tools/turbinia_job_graph.py
> Migrate job graph generator to use new manager

- turbinia/task_manager.py
We have a var in the config file, let's use it!
> Make use of SLEEP_TIME config var

- turbinia/lib/libcloudforensics.py
This is due to https://github.com/log2timeline/l2tdevtools/issues/465
> Removed sleuthkit from pre installed packages

- turbinia/client.py
- turbinia/task_manager.py
- turbinia/turbiniactl.py
... Also adding sleep between task scheduling to smear out where tasks are executed.
> Update client output and change log level

- turbinia/turbiniactl.py
This flag isn't really needed since we can just check the config.
Fixes #374
> Remove -C flag

- turbinia/config/turbinia_config.py
> Clarify state/task manager config comments

- turbinia/client.py
- turbinia/client_test.py
- turbinia/turbiniactl.py
- turbinia/workers/__init__.py
- turbinia/workers/analysis/jenkins.py
- turbinia/workers/analysis/wordpress.py
- turbinia/workers/hadoop.py
- turbinia/workers/sshd.py
- turbinia/workers/tomcat.py
- Also Fixes #380 by making sure we have default values correct
- Also Fixes task wait loop to only print updates when something has changed
> Add report priority enum

- turbinia/lib/libcloudforensics.py
> Add docker-explorer-tools to the GCE install script

- turbinia/lib/utils.py
- turbinia/processors/google_cloud.py
- turbinia/workers/analysis/jenkins.py
- turbinia/workers/analysis/wordpress.py
- turbinia/workers/hadoop.py
> Some fixes for Python3

- turbinia/workers/__init__.py
> Fix version mismatch error return

- tools/turbinia_job_graph.py
Also make magic "list" value that will list out the engine and output format types.
> Add graph engine option to graph generation

- turbinia/client.py
- turbinia/state_manager.py
- turbinia/turbiniactl.py
- Also reverts part of #458 which causes tasks to disappear (by default) after they are started.
> Fix datastore data type for instance var

- turbinia/config/logger.py
- turbinia/turbiniactl.py
> Fix format strings for exceptions

- turbinia/client.py
- turbinia/client_test.py
- turbinia/turbiniactl.py
- turbinia/workers/finalize_request.py
Creating as normal PR to see the test results. Let me know if a function-only implementation, such as the one in state_manager is a better fit.
> Proposed fix for issue #453

- turbinia/turbiniactl.py
... it needed `action='store_true'`
> Fix --copy_only flag

- requirements.txt
> Pin google-cloud-pubsub to 1.4.2

- turbinia/client.py
- turbinia/client_test.py
- turbinia/config/turbinia_config_tmpl.py
- turbinia/jobs/manager_test.py
- turbinia/task_manager.py
- turbinia/task_manager_test.py
- turbinia/turbiniactl.py
* Add a few expensive jobs to the default `DISABLED_JOBS` list in the config
* Allow disabled jobs to be whitelisted
* Disable Jobs disabled in the config on the Server as well 
* Add tests for whitelists/blacklists
> Allow disabled jobs to be whitelisted

- turbinia/client.py
Signed-off-by: Theo Giovanna <gtheo@google.com>
> Add missing region parameter to ExecuteFunction

- requirements.txt
The upstream issues are fixed now.
> Unpin pubsub dependency

- setup.py
... Also update other dependency versions.
> Add docker-explorer to worker dependencies

- .travis.yml
Also deleting unneeded history file
> Remove py2 testing/support

- turbinia/client.py
- turbinia/client_test.py
- turbinia/turbiniactl.py
Adds in the request status request view
> Implements status request view

- turbinia/turbiniactl.py
* Added 'd' to compressedirectory
* Fixed source_path cli parameter to local_path
> Fix spelling error and comresseddirectory source_path parameter.

- turbinia/e2e/googleclouddisk.sh
- turbinia/e2e/setup-gce.sh
- turbinia/e2e/teardown-gce.sh
A Turbinia e2e test including:
* setup of Turbinia Terraform environment
* a e2e test for the 'googleclouddisk' job
* tear down and cleanup of the Terraform environment
This e2e test is meant to be run from Jenkins but can also run standalone if the GCP project and credentials are setup correctly.
> Turbinia e2e test - googleclouddisk

- turbinia/config/__init__.py
> Do not read config from cache when file is specified

- .travis.yml
- requirements.txt
Fixes: https://github.com/google/turbinia/issues/604
> Pin six package to fix dependency issue

- docker/server/Dockerfile
- docker/worker/Dockerfile
* Use python3 for our docker images
* Build Turbinia from source instead of using pypi package (#608)
> Change Dockerfiles to python3 and build from src.

- docker/server/Dockerfile
- docker/worker/Dockerfile
- docs/user/operational-details.md
- requirements.txt
- turbinia/client.py
- turbinia/config/__init__.py
- turbinia/config/turbinia_config_tmpl.py
- turbinia/task_manager.py
* Add Prometheus scaffolding code to server and worker
* Add address and port parameters to Turbinia configuration
* Expose port in docker build configuration
* Add 1 sample Prometheus Gauge to server
> Instrument Turbinia with Prometheus.

- turbinia/turbiniactl.py
> Replace hardcoded tmp folder with config value TMP_DIR.

- docker/prometheus/Dockerfile
- docker/prometheus/README.md
- docker/prometheus/build.sh
- docker/prometheus/start.sh
* Create monitoring container
* Add Prometheus 
* Add Google Stackdriver/Monitoring sidecar
> Add Prometheus container with Stackdriver sidecar.

- turbinia/workers/artifact.py
> Ignore hashes.json from the output of image_export.py

- turbinia/workers/sshd.py
See https://github.com/google/turbinia/issues/629#issuecomment-731249768
> Fix SshdConfigAnalysis task PasswordAuthentication detection

- turbinia/client.py
> Serialize Evidence when running locally

- turbinia/e2e/setup-gce.sh
Terraform does *not* have a latest package to download :(
> Update terraform version in e2e test setup

- turbinia/config/logger.py
Remove syslog handler for now.
> Remove syslog handler.

- dfvfs_requirements.txt
Pin dfvfs and dependencies to stable version.
> Pin dfvfs to stable version.

- turbinia/lib/utils.py
JenkinsAnalysis job is the only job to use this function and it currently failes as the image_extract command is not running with sudo.
> Add sudo to extract_files() command.

- turbinia/turbiniactl.py
Fixes a reference error when stackdriver logging is enabled.
> Move cloud imports earlier for turbiniactl

- turbinia/__init__.py
- turbinia/workers/plaso.py
- turbinia/workers/psort.py
Add temporary_directory option to both log2timeline and psort execution.
> Add temp folder to plaso task commands

- turbinia/evidence.py
- turbinia/jobs/jupyter.py
- turbinia/processors/mount_local.py
- turbinia/workers/__init__.py
... Also update Datastore from the worker after it completes and add a couple log messages.
> Fix jupyter Task creation

- docker/worker/Dockerfile
- turbinia/config/turbinia_config_tmpl.py
- turbinia/evidence.py
- turbinia/lib/dfvfs_classes.py
- turbinia/lib/dfvfs_classes_test.py
- turbinia/processors/mount_local.py
- turbinia/processors/mount_local_test.py
- turbinia/processors/partitions.py
- turbinia/turbiniactl.py
- turbinia/workers/partitions.py
Added BitLocker support using dfVFS and libbde
> BitLocker volume support

- docs/developer/develop-vscode.md
- docs/developer/developing-new-tasks.md
- docs/user/how-it-works.md
- docs/user/install-manual.md
- turbinia/client.py
- turbinia/config/turbinia_config_tmpl.py
- turbinia/e2e/googleclouddisk.sh
- turbinia/evidence.py
- turbinia/jobs/volatility.py
- turbinia/lib/docker_manager.py
- turbinia/notify.py
- turbinia/output_manager_test.py
- turbinia/processors/archive.py
- turbinia/processors/google_cloud.py
- turbinia/processors/mount_local.py
- turbinia/state_manager_test.py
- turbinia/workers/__init__.py
- turbinia/workers/volatility.py
Improving some of the documentation and comments here.
> spelling improvements

- turbinia/workers/docker.py
- turbinia/workers/redis.py
Fixes #757 and #762 
* redis-analysis-task: open file in binary mode as we are writing bytes....
* docker-explorer task: put cli parameter in correct position
> Fix redisanalysis and dockerexplorer tasks.

- turbinia/workers/__init__.py
> Verify JSON serializes and stringify saved errors

- turbinia/client.py
- turbinia/state_manager.py
* Fixes #749 
* Also changes filtering done by Redis querying code to match the Datastore version by logically making each filter parameter be an `AND` instead of an `OR`.
> Add user to redis state manager calls

- turbinia/client.py
- turbinia/workers/__init__.py
- turbinia/workers/workers_test.py
> Fix histogram duplicate registry

- turbinia/processors/partitions.py
> Add import for TurbiniaException

- docker/worker/cloudbuild.yaml
- turbinia/__init__.py
.. Also fix unrelated YAPF error.
> Fix worker cloud build config

- monitoring/grafana/dashboards/turbinia-application-metrics.json
- monitoring/grafana/provisioning/dashboards/turbinia.yaml
- monitoring/grafana/provisioning/datasources/prometheus.yaml
- monitoring/prometheus/prometheus.yaml
- turbinia/config/turbinia_config_tmpl.py
This PR adds in configuration files for the monitoring infastracture that can be deployed alongside with Turbinia. It contains configuration files for provisioning grafana and prometheus as well as a templatized dashboard for Turbinia Application metrics.
> Monitoring dashboards

- turbinia/workers/grep.py
> Write grep patterns file as bytes

- turbinia/workers/docker.py
* move json load to try/except block
* add de.py output to error so we can see if/what we need to tune if the de.py output changes
fixes #810
> Fix DockerContainerEnumeration JSON decoding bug

- turbinia/client.py
- turbinia/lib/docker_manager.py
- turbinia/workers/docker.py
Fixes #758 and #764 
* When DOCKER_ENABLED=True we need to *not* fail when there is no docker daemon
* When no docker library folder is found we need to return nothing instead of erroring out of the dockeranalysis task.
> Fix docker task and runner related issues.

- turbinia/workers/analysis/jupyter.py
> Fix jupyter analysis task encoding

- turbinia/client.py
* move log initialisation separate function
* add is_client parameter to disable file logging
> Move initialising logging to setup() function

- docker/worker/Dockerfile
- turbinia/workers/artifact.py
See https://github.com/google/turbinia/issues/629#issuecomment-731263422
> Remove hashes.json check

- docker/local/docker-compose.yml
- requirements.txt
Fixes #841 
Fixing with the minimum version needed to prevent upstream issues (eg dftimewolf).
> Fix dependency error in google cloud libs.

- turbinia/turbiniactl.py
... or when an explicit log file path has been passed in.
Fixes #788
> Only set up file log handlers for server/worker

- .devcontainer/devcontainer.json
> Run redis-server on subsequent start of devcontainer

- tools/gcf_init/index.js
- tools/gcf_init/package.json
> Update GCFs to run with new datastore module and nodejs runtime.

- tools/gcf_init/deploy_gcf.py
This should now match what is in the terraform deployment.
> Update GCF deployment script

- docker/worker/Dockerfile
- test_data/shadow
- turbinia/client.py
- turbinia/config/recipes/all.yaml
- turbinia/jobs/__init__.py
- turbinia/jobs/linux_acct.py
- turbinia/workers/analysis/linux_acct.py
- turbinia/workers/analysis/linux_acct_test.py
Incorporates comments from the CL
> Shadow cracking worker

- CONTRIBUTING.md
- docs/user/install.md
- tools/update-gcp-infra.sh
- turbinia/lib/recipe_helpers.py
- fix typo spelling grammar and replace to correct words with reference from [merriam webster](merriam-webster.com)
- fix url contributing path at ```CONTRIBUTING.md```
testing not include because just replace typo and url to correct one
> fix: typo spelling grammar and change url contributing

- requirements.txt
> Fix Google Cloud library dependencies.

- docker/server/start.sh
- docker/worker/start.sh
This is mainly so that we can add debug flags dynamically.
> Add TURBINIA_EXTRA_ARGS to start.sh

- turbinia/workers/plaso.py
> Add --storage_file parameter to log2timeline invocation

- turbinia/workers/hadoop.py
Now that https://github.com/forensicanalysis/artifacts/pull/47 is landed
> Update Hadoop analyzer to use timeline files

- docs/user/install.md
Updated pipenv link as sphinx saying its a broken link now and causing unit tests to fail
> Updated pipenv broken link causing tests to fail

- turbinia/task_utils.py
- turbinia/task_utils_test.py
> Fix TaskLoader and add tests

- turbinia/output_manager.py
- turbinia/output_manager_test.py
- turbinia/workers/__init__.py
> Prepend the request ID to the output path

- turbinia/config/__init__.py
- turbinia/config/turbinia_config_tmpl.py
- turbinia/task_utils.py
- turbinia/workers/__init__.py
- turbinia/workers/dfdewey.py
- turbinia/workers/workers_test.py
* Send dfDewey datastore config to the worker through environment variables
* Minor changes for dfDewey migration to OpenSearch
> dfDewey datastore config

- turbinia/processors/google_cloud.py
- turbinia/processors/mount_local.py
Basic metrics to track non existing disk paths and failed local unmount attempts
> Added metrics for disk attach/detach failure

- .devcontainer/devcontainer.json
mount /dev path for access to google cloud disks
> mount /dev path for access to google cloud disks

- turbinia/turbiniactl.py
> Bugfix: add missing format() call to format string

- docs/developer/contributing.md
> Fix broken Github links in docs

- turbinia/client.py
Until https://github.com/google/turbinia/issues/999 is fixed.
> Give appropriate error for not implemented close_tasks method

- turbinia/workers/file_system_timeline.py
> improve exception handling (FileSystemTimelineTask)

- turbinia/client.py
> use default recipe only if recipe not specified

- turbinia/lib/recipe_helpers.py
> 'message' referenced before assignment in recipe_helpers.validate_recipe

- turbinia/lib/recipe_helpers_test.py
> Write tests for recipe implementation

- turbinia/task_manager.py
> Use correct task reference in manager

- turbinia/workers/cron.py
> Catch errors parsing input file in cron Task

- docs/developer/developing-new-tasks.md
- docs/user/using-docker.md
- turbinia/client.py
- turbinia/output_manager.py
Hello, everyone in the community! 🙂
I found some typos during code analysis and fixed them.
I hope it's a good first opportunity to contribute to turbinia.
> Fix: Typo for docs, client, output_manager

- turbinia/task_manager.py
> Fix server task timeout format string

- turbinia/state_manager.py
> Fix task filtering in State Manager get_task_status()

- turbinia/client_test.py
- turbinia/turbiniactl.py
- turbinia/turbiniactl_test.py
> Fix turbiniactl cli flags not properly set for default recipe

- turbinia/processors/partitions.py
- turbinia/workers/partitions.py
Updates to debug logging added in #1045
> Updates to partition debug logging

- turbinia/e2e/googleclouddisk.sh
- turbinia/evidence.py
- turbinia/processors/partitions.py
- turbinia/processors/partitions_test.py
- turbinia/workers/partitions.py
Specify the partition location in preprocessor partition enumeration so that dfVFS only returns the relevant path_spec
> Specify location in preprocessor partition enumeration

- docker/worker/Dockerfile
- turbinia/workers/file_system_timeline.py
* Stop using deprecated GetBodyfileEntries method
* Fix partition selection code and add support for encrypted volumes
> FileSystemTimelineTask Updates

- turbinia/turbiniactl.py
> Fix auto-upload from client

- turbinia/task_manager.py
Update task_manager to set psq only when server is running since it is not needed for clients and it initiates unneeded cloud auth
> Update task_manager to set psq only when server is running

- docker/worker/Dockerfile
- turbinia/config/rules/pgsql_from_program.yar
- turbinia/workers/analysis/loki.py
While we figure out the direction Turbigma will take, a quick PR to make a place for custom YARA rules to be run by the Loki analyzer.
> Custom YARA rules

- turbinia/lib/recipe_helpers.py
- turbinia/message.py
- turbinia/task_manager.py
- turbinia/task_utils.py
- turbinia/worker.py
Clean up some unused import statements and import order
> Clean up unused imports

- turbinia/config/rules/redis_replicaof.yar
- turbinia/workers/analysis/loki.py
Introduces a YARA rule that detects recent exploitations that we've seen against Redis, as well as enables Kinsing detection rules by increasing the maximum file size of scanned files
> Redis exploitation detection

- turbinia/evidence.py
- turbinia/evidence_test.py
- turbinia/turbiniactl.py
Adding descriptive evidence names
Fixes: #468
> Evidence names

- docker/vscode/psq-config.sed
- docker/vscode/redis-config.sed
Disable jobs from dev containers
> Disable yaraanalysisjob and hindisght job

- docs/README.md
- docs/user/install.md
... Also add minimal README file for the documentation directory to point to the official readthedocs version.
> Add deprecation notice for terraform

- requirements.txt
- turbinia/e2e/e2e-local.sh
- turbinia/workers/binary_extractor.py
> Pin redis to match Plaso requirement and remove deprecated --no_vss option

- turbinia/workers/plaso.py
> Do not hash files larger than 1GB by default in PlasoTask

- docker/worker/Dockerfile
- turbinia/config/rules/pgsql_from_program.yar
- turbinia/config/rules/suspicious_cron.yar
* Tune existing rules to catch more badness
** Babelfish built on Postgres
** Previously seen `pg_mem` cryptominer embedded in cronjobs
* Swap the order of the password lists to more quickly catch the commonly used ones
> Rule Tuning

- turbinia/config/__init__.py
Fixes #1109 
Use up to date library and method to load a module from a source file.
> Fix deprecation warning in config module

- docker/worker/Dockerfile
- docs/developer/developing-new-tasks.md
- turbinia/evidence.py
- turbinia/jobs/binary_extractor.py
- turbinia/jobs/bulk_extractor.py
- turbinia/jobs/dfdewey.py
- turbinia/jobs/file_system_timeline.py
- turbinia/jobs/http_access_logs.py
- turbinia/jobs/jenkins.py
- turbinia/jobs/jupyter.py
- turbinia/jobs/linux_acct.py
- turbinia/jobs/partitions.py
- turbinia/jobs/plaso.py
- turbinia/jobs/redis.py
- turbinia/jobs/sshd.py
- turbinia/jobs/tomcat.py
- turbinia/jobs/windows_acct.py
- turbinia/jobs/wordpress_creds.py
- turbinia/jobs/worker_stat.py
- turbinia/processors/mount_local.py
- turbinia/turbiniactl.py
Hopefully this is as the previous one was. Only difference should be that we fixed formatting using yapf and pulled the newest changes from the main repo.
> Implemented ExpertWitnessFormat for disk 2

- k8s/tools/update-gke-infra.sh
This adds two flags to show the first or last N lines for each pod in the cluster.
> Add tail/head logs flags to update-gke-infra.sh

- turbinia/client.py
- turbinia/evidence.py
- turbinia/lib/file_helpers.py
- turbinia/lib/utils.py
- turbinia/message.py
- turbinia/notify.py
- turbinia/processors/docker.py
- turbinia/processors/google_cloud.py
- turbinia/processors/mount_local.py
- turbinia/processors/partitions.py
- turbinia/processors/resource_manager.py
- turbinia/state_manager.py
- turbinia/task_manager.py
- turbinia/tcelery.py
- turbinia/turbiniactl.py
- turbinia/worker.py
- turbinia/workers/analysis/jenkins.py
- turbinia/workers/analysis/linux_acct.py
- turbinia/workers/analysis/postgresql_acct.py
- turbinia/workers/analysis/windows_acct.py
- turbinia/workers/analysis/wordpress_creds.py
- turbinia/workers/analysis/yara.py
- turbinia/workers/docker.py
- turbinia/workers/partitions.py
- turbinia/workers/volatility.py
- turbinia/yapf_test.py
Fixes #1125 
Other small fixes:
- Specify encoding when opening files (if encoding is unspecified, then the encoding will be platform-dependent).
- Added missing docstrings.
> Use a consistent name for exceptions

- turbinia/config/rules/pgsql_from_program.yar
- turbinia/config/rules/suspicious_cron.yar
https://www.yugabyte.com/
Distributed Cloud database based on Postgres.
> Expand Postgres compromise rule to cover Yugabyte

- web/package-lock.json
- web/package.json
Update web dependencies to latest versions
> update web versions

- tools/fraken/go.mod
- tools/fraken/go.sum
Bring more up to date and hopefully fix the crashing
> Update go-yara version

- turbinia/workers/analysis/jenkins.py
> Add optional /home/ to Jenkins path

- turbinia/__init__.py
- turbinia/client.py
- turbinia/client_gcp_test.py
- turbinia/config/turbinia_config_tmpl.py
- turbinia/evidence.py
- turbinia/turbiniactl.py
- turbinia/turbiniactl_test.py
> Cloud provider fix

- turbinia/evidence.py
- turbinia/processors/mount_local.py
Not all the attributes were being created properly so I added some defaults and also check that they exist before being used in the pre-processors.
> Make sure partition attributes are set

- web/src/App.vue
- web/src/components/RequestList.vue
- web/src/components/TaskDetails.vue
- web/src/components/TaskList.vue
- web/src/utils/RestApiClient.js
* Adds TaskList view which is shown by clicking right of a request and shows processing details of Tasks related to the Request.
* Adds TaskDetails view which is shown by clicking on a Task and displays all details of a given Task.
* Adds the ability to export Task output from the UI via the TaskDetails view.
* Adds the ability to export Report output from the UI via the RequestList view.
* Clean up UI adding various icons displaying its status as well as a progress circle that measures total tasks - completed and failed tasks as best guess estimate.
> Web UI V2 - TaskList TaskDetails and export task and request output

- turbinia/api/cli/requirements.txt
Remove turbinia-api-client package
> Remove turbinia-api-client package

- k8s/tools/deploy-pubsub-gke.sh
GKE e2e tests failing due to not having same logic to enable node autoscaling/variables changed
> Add node autoscaling to pubsub script

- turbinia/config/turbinia_config_tmpl.py
- web/package-lock.json
- web/package.json
Update web packages to their latest versions and update default WEB_UI path
> update web versions to latest and update default WEB_UI path

- README.md
- turbinia/api/cli/README.md
- turbinia/api/cli/turbinia_client/core/groups.py
> API CLI tool documentation

- docker/worker/Dockerfile
- turbinia/config/turbinia_config_tmpl.py
- turbinia/evidence.py
- turbinia/processors/mount_local.py
- turbinia/processors/mount_local_test.py
- turbinia/processors/partitions.py
Adding LUKS encryption support through evidence pre-processor using libluksde.
> Add LUKS Encryption Support

- k8s/tools/check-lockfile.py
Log events for GKE preStop actions
> Add logging to check-lockfile script

- turbinia/api/models/request_status.py
> Refactor request status logic

- turbinia/turbiniactl.py
Fixes issues in turbiniactl when loading API server module
> Late import Turbinia API server

- turbinia/api/cli/setup.py
Bump turbinia-client version for PyPi package.
> Update turbinia client version

- docker/api_server/Dockerfile
- docker/oauth2_proxy/Dockerfile
- docker/server/Dockerfile
- docker/worker/Dockerfile
Add apt-get upgrade commands to Docker build files to update to latest stable software packages on image build.
> Add apt-get upgrade commands to Docker build files.

- docker/worker/Dockerfile
- turbinia/processors/google_cloud.py
- turbinia/processors/mount_local.py
- turbinia/task_manager.py
- turbinia/workers/__init__.py
Change Gauge metrics type to Counter.
- fixes #1320
> Change metric type Gauge to Counter

- web/src/components/RequestList.vue
- web/src/components/TaskDetails.vue
Sets correct file type for download.
Download file is actually  a .tgz file.
> Fix download extension

- turbinia/api/cli/turbinia_client/core/commands.py
> Fix API client typo

- .github/ISSUE_TEMPLATE/feature_request.yaml
Re-order issue template items.
> Re-order Issue template items

- docker/worker/Dockerfile
Add bitlocker, apfs and luks dependency utilities to worker so partition code works.
- fixes #1384 
- [NA] Unit tests added.
- [NA] Documentation updated.
> Add utilities for partition code to worker.

- pyproject.toml
update version to 20231116 for release
> update version to 20231116 for release

- turbinia/api/models/request_status.py
- turbinia/api/models/tasks_statistics.py
- turbinia/api/models/workers_status.py
- turbinia/state_manager.py
- turbinia/worker_test.py
- turbinia/workers/__init__.py
> Fix various typos

- turbinia/api/cli/turbinia_client/helpers/formatter.py
Reduce report header size for tasks below threshold
> Reduce report header size for tasks below threshold

- docker/vscode/Dockerfile
> Fix mispelled devcontainer

- turbinia/task_manager.py
> Add request ID to task manager logging

- turbinia/workers/analysis/linux_acct.py
- turbinia/workers/analysis/linux_acct_test.py
The backup shadow file can be useful for determining what the password was, if the attackers changed it post-compromise.
Try and crack it, and also indicate where we got each cracked password from.
> Also try bruteforcing the shadow backup file

- docker/oauth2_proxy/Dockerfile
- docker/oauth2_proxy/start.sh
Override default timeout setting in oauth2-proxy. Fix curl fetch error in Dockerfile
- fixes #
> Updates to oauth2-proxy dockerfile and entrypoint

- turbinia/tcelery.py
Only log message received when we have actual requests.
> Suppress noisy debug message

- docs/user/install.md
- turbinia/config/turbinia_config_tmpl.py
Updates Docker install docs to retrieve the release configuration file instead of master and add `file_system_timeline` dep back in
- fixes #
- [X ] Documentation updated.
> Update docker install docs and add file_system_timeline back in

- pyproject.toml
Update the version to 20240412.1.  I'll cut the new .1 release to patch in this version update.
> Update version to 20240412.1

- turbinia/api/routes/ui.py
> Fix path traversal vulnerability in UI router

- docker/tests/Dockerfile
- poetry.lock
- pyproject.toml
- turbinia/jobs/imports_test.py
- turbinia/output_manager_test.py
- turbinia/redis_client.py
- turbinia/workers/analysis/linux_acct_test.py
- turbinia/workers/workers_test.py
- web/package-lock.json
Updates dependencies and Turbinia version for a new release. Minor unit test and style fixes.
- fixes #
> Version updates and minor test fixes

- pyproject.toml
- turbinia/config/turbinia_config_tmpl.py
Temporarily add back config var and update version for a point release.
> Temporary config change revert and version bump

- turbinia/e2e/e2e-local.sh
- turbinia/e2e/run-e2e-gke.sh
Updates to e2e test scripts.
- fixes #
> Update e2e testing scripts

- turbinia/api/api_server.py
- turbinia/config/logger.py
Fixes API logging issue and logs to Turbinia ```LOG_DIR```
- fixes #1424
> Fix APi server logging

- turbinia/e2e/e2e-local.sh
- turbinia/e2e/run-e2e-gke.sh
Fixes a logic error that may result in the script never returning properly.
- fixes #
> Update e2e test

- turbinia/lib/llm_libs/vertex_ai_lib.py
- turbinia/workers/analysis/llm_analyzer.py
migrate Vertex AI LLM analyzer to Gemini 1.5 pro
> migrate Vertex AI LLM analyzer to Gemini 1.5 pro

- docker/controller/Dockerfile
Update controller dockerfile to use Poetry
- fixes #
> Update dockerfile for Controller container

- docker/local/README.md
- docs/developer/develop-minikube.md
- k8s/tools/get-system-pods-list.py
- turbinia/config/rules/suspicious_cron.yar
- turbinia/config/turbinia_config_tmpl.py
- turbinia/e2e/run-e2e-gke.sh
- turbinia/jobs/llm_artifacts_analyzer.py
- turbinia/lib/llm_libs/llm_client.py
- turbinia/lib/llm_libs/vertex_ai_lib.py
- turbinia/message.py
- turbinia/task_manager.py
- turbinia/workers/analysis/analyzer_output.py
- turbinia/workers/artifact.py
Did some smaller typo checks / fixes across the repo.
Hope that helps.
> smaller typo fixes

- turbinia/workers/analysis/yara.py
Upgrade yara test `info`s to `error`s
Also, I have cleaned the Github Action caches, which I think was the actual problem.
Let's see.
Fixes #1568
> Change logging level on errors

- tools/fraken/go.mod
- tools/fraken/go.sum
> Update go-yara for Fraken

- pyproject.toml
> Update pyproject.toml version

- README.md
Add maintenance and OpenRelik message to README.
> Add maintenance and OpenRelik message to README.
