- turbinia/config/pylintrc
We could also put this somewhere in a top-level directory, but I didn't want to copy all of the utils dir, and I'm not sure what else we might put there, so I just put it in the turbinia/config dir for now.  I also took a look at the timesketch copy of pylintrc, and there were several new updates to the one in plaso that looked useful so I copied that one instead.
> Add pylintrc copied from Plaso.

- turbinia/evidence.py
- turbinia/workers/__init__.py
What do you think about this as a base implementation for {pre,post}-processing could work?  I realized that almost all of the cases for preprocessing are related to specific evidence types, and we can use the normal inheritance mechanisms here to make things work.  For example, the GoogleCloudDisk.preprocess() can do the attaching, and then it can call its parent's (RawDisk's) preprocess() to do the actual local mounting of the disk (if we wanted to actually mount it) too.
If we have a non-evidence specific type of pre/post processing that we want to do, I think we can implement that as decorators for the TurbiniaTask.run() methods, but I wasn't sure if we had a good use-case for that, so I didn't want to add it until we needed it.
> Add pre/post-process hooks for evidence

- tests/evidence.py
- tests/pubsub.py
- turbinia/evidence.py
- turbinia/pubsub.py
- turbinia/task_manager.py
- turbiniactl
This adds a listener to the Turbinia server that will listen for incoming requests to process evidence.  It also changes turbiniactl to send evidence over pubsub when it is not operating as a server.
> Add PubSub interface to process incoming requests

- turbinia/config/__init__.py
- turbinia/config/turbinia_config.py
- turbinia/evidence.py
- turbinia/processors/mount_local.py
- turbiniactl
Note:  Also needed to fully support this type of evidence format is a task to do the conversion from raw image files in GCS to GCP PD with embedded raw images (Issue #63 ).
> Process GCP persistent disks with embedded raw image

- turbinia/task_manager.py
- turbinia/workers/__init__.py
- turbinia/workers/plaso.py
This will catch exceptions and set the TurbiniaResult appropriately.  It also moves the TurbiniaResult setup out of the run function and into the decorator.  In the future we can potentially move other results handling into the decorator as well.  Fixes #70.
> Add results and exception handler decorator for workers

- turbinia/state_manager.py
- turbinia/task_manager.py
- turbinia/workers/__init__.py
- turbiniactl
- Also add --all_fields for more verbose turbiniactl status output
- Also small comment in state_manager
>  Plumb the request_id into tasks/datastore

- turbinia/workers/__init__.py
- turbiniactl
This means copying the request_id into the TurbiniaTaskResult and then copying it when the result closes.  Also updated some comments.
> Make sure new evidence objects have their ancestor's request_id

- requirements.txt
- setup.py
We need to pin google-cloud-pubsub to version 0.26.0 before we fix our call to pubsub client.
Also read from requirements.txt in setup.py so we can handle versions there.
> Pin dependency versions

- requirements.txt
So, this gives the secure "extras" for urllib3, and this (besides making it more secure) squashes the SSL warnings.  I'm not positive that this is the idiomatic way to handle this kind of thing, so let me know what you think.
> Add urllib3 with 'secure' extras to requirements

- turbinia/workers/__init__.py
- turbinia/workers/plaso.py
- turbinia/workers/psort.py
This saves a few lines of boiler plate in the task code, and also fixes a bug where evidence wasn't being saved correctly after the refactor into the new execution method (because close was being called before the evidence was added).
> Move saving of new evidence into execution handler

- turbinia/task_manager.py
Need to do this, otherwise, the psort job will match against PlasoCsvFile evidence objects (which is the output of the psort job) because it is a subclass of the PlasoFile evidence object.
> Strict type check when matching evidence to jobs

- turbinia/config/__init__.py
- turbinia/config/turbinia_config.py
- turbinia/evidence.py
- turbiniactl
Also adds 'copyable' attribute for evidence types that we can copy around (e.g. PlasoFile).
> Add Checks to avoid requests to incompatible instances

- turbinia/config/__init__.py
Note that it will still search all of these paths for files with these names.  Order is homedir, etc, source tree (so that the users config will override the global config).
> Look for config at /etc/turbinia/turbinia.conf too

- turbinia/workers/__init__.py
We also want to save the local path for later retrieval through `turbiniactl status` in the cases where we're running with a shared FS.
Ignore the config change, I'll rebase it before submission (just wanted to get this in first).
> Save local evidence output path too

- run_tests.py
- setup.py
- tests/config/config.py
- tests/evidence.py
- tests/output_manager.py
- tests/pubsub.py
- tools/gcf_init/deploy_gcf.py
- turbinia/__init__.py
- turbinia/config/__init__.py
- turbinia/config/logger.py
- turbinia/config/turbinia_config.py
- turbinia/evidence.py
- turbinia/jobs/__init__.py
- turbinia/jobs/be.py
- turbinia/jobs/plaso.py
- turbinia/jobs/psort.py
- turbinia/jobs/worker_stat.py
- turbinia/lib/google_cloud.py
- turbinia/output_manager.py
- turbinia/processors/google_cloud.py
- turbinia/processors/mount_local.py
- turbinia/pubsub.py
- turbinia/state_manager.py
- turbinia/task_manager.py
- turbinia/workers/__init__.py
- turbinia/workers/be.py
- turbinia/workers/plaso.py
- turbinia/workers/psort.py
- turbinia/workers/worker_stat.py
In response to #15.
Prepended "# -- coding: utf-8 --" to all the Python files. This line defines the default encoding in those files. For details, see https://www.python.org/dev/peps/pep-0263/.
Added future's unicorn_literals to make strings as unicorn by default.
Removed the trailing letter u from unicorn strings.
> Added future's unicode_literals to make strings as unicorn by default.

- turbinia/output_manager.py
- turbinia/workers/__init__.py
Fixes #122 
- Creates new OutputManager object
- Moves output management related functions to new object
- Refactors write() methods into copy_to() and copy_from() to support copying data in both directions
- Adds evidence specific save/retrieve methods
- Adds hooks to copy evidence data back from GCS when it is marked "copyable", and we don't have a shared filesystem.
> Refactor output manager to support copying back data

- turbinia/output_manager.py
- turbinia/workers/__init__.py
We want to close results if possible, but it can also cause errors.  Generally this adds more error handling and logging to the process
> Auto close result objects after failures

- turbinia/output_manager.py
- turbinia/workers/__init__.py
- turbinia/workers/worker_stat.py
This is a follow-up PR to #142.  The previous PR moved the output manager related functions to the output_manager module, and this PR moves the task members that hold a reference to this from TurbiniaTaskResult to TurbiniaTask.  This is to make result handling more resilient because when there were uncaught problems with the TurbiniaTaskResult, keeping this as a member would cause problems when returning and serializing it.
> Move output_manager from TurbiniaTaskResult to TurbiniaTask

- turbinia/evidence.py
This should have been in one of the previous PRs, but I had missed adding it somehow.
> Add saved_path members to Evidence

- tests/output_manager.py
The method names were changed after a previous refactor.
> Fix output manager tests

- tests/config/config.py
- tests/output_manager.py
This is to prevent future tests from being affected since they are module level attributes.
> Fix config and output_writer tests

- tests/config/config.py
This ensures that the config tests aren't affected by other tests that may have pre-loaded the config.
> Explicitly set empty config in tests

- setup.py
- turbinia/turbiniactl.py
- `entry_points / console_scripts` seems to be the suggested replacement for `scripts` (and is more flexible): https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point
My motivation for this change was to allow importing of `turbiniactl` directly. This doesn't change anything about running `turbiniactl` -- everything is exactly the same (i.e. you still get a `turbiniactl` in your path after a `python setup.py install`). But now with the added benefit of *also* being able to do `from turbinia import turbiniactl` (which makes building turbinia in our build system easier, since we use par files to self-contain python packages & their imports; and I'm sticking some python management on top of `turbiniactl`).
> Update setup.py to use newer 'entry_points' param

- .gitignore
- MANIFEST.in
- requirements.txt
- setup.py
This PR remove the dependency on Plaso for the client only install. If you are installing a worker you now need to do: pip install turbinia[worker]
Also, this PR fixes a bug where pip v10.x couldn install the package.
> Install Plaso only for workers

- requirements.txt
- tests/pubsub.py
- turbinia/pubsub.py
- turbinia/task_manager.py
PubSub no longer supports a pull mechanism, so this creates a small callback that adds incoming pubsub messages to a queue that can be checked similar to how we were doing it before.  It also separates out the publisher/subscriber clients and will auto-create the topics and subscriptions.
> Update PubSub and PSQ to the latest packages 

- turbinia/pubsub.py
- turbinia/task_manager.py
Apparently using google.api_core directly is bad since it's considered an internal/private interface, and the proper exception classes are in google.cloud.exceptions.
> Use non-private exceptions

- turbinia/client.py
- turbinia/client_test.py
- turbinia/pubsub.py
- turbinia/task_manager.py
- turbinia/turbiniactl.py
This does a few things, but the net result is that we only load:
- pubsub publisher from the client
- pubsub subscriber from the server
- No pubsub in psqworker
- No client object in turbiniactl when we are running server or psqworker
It also:
- Starts to pull things out of the task manager, but there are still a few other components, so I filed #205.
- Separated the Server/PSQWorker client objects from TurbiniaClient 
- Also cleaned up some lint errors along the way
> Load only required pubsub features per component type

- turbinia/client.py
- turbinia/state_manager.py
- turbinia/state_manager_test.py
- turbinia/workers/__init__.py
- turbinia/workers/grep.py
- turbinia/workers/workers_test.py
This PR does a few things:
- Catches a few errors/exceptions within the Datastore State manager (Datastore has a small string size limit)
- Handles invalid return values from the Task run() function
- Verifies that Evidence to be added in the Task execution() helper method has a valid and non-empty local path before adding it to be created
- Adds some more tests for affected modules
- Fixes up a few lint errors along the way
> State manager and run_wrapper fixes

- turbinia/celery.py
- turbinia/client.py
- turbinia/evidence.py
- turbinia/output_manager.py
- turbinia/state_manager.py
- turbinia/task_manager.py
Addresses #201. If/else clauses around any GCloud-only or Celery-only imports. I left the pubsub and celery modules alone, since we only import them in specific cases already.
Tested by commenting out GCloud dependencies (requirements.txt) and installing `turbinia[local]` fresh; processing works as expected without any import errors. Tests pass -- except the GCloud ones and the client tests (written for PSQ), can you test those?
> Selectively import modules

- requirements.txt
Pinning this for now until this is fixed (the upstream dependency requirements seem to be incorrect):
https://github.com/GoogleCloudPlatform/google-cloud-python/issues/6128
This will allow us to move forward with the dftimewolf integration which has dependencies (grr-client-api) which depend on an incompatible version of protobuf.
> Pin google-cloud-pubsub==0.35.4

- turbinia/client.py
While testing internally, we encountered an issue documented here: https://github.com/celery/celery/issues/4113. Forcing celery workers to be single threaded (by adding `--pool=solo`) fixes this issue.
> Force celery workers to be single threaded

- requirements.txt
The minimum library versions are not set correctly for some of the upstream cloud libraries so we'll need to pin them for now.  See the following for more details on the bug: 
https://github.com/googleapis/google-cloud-python/issues/6390
This can be removed once grr-client-api updates its pinned version of protobuf.  The grr-client-api library gets pulled in from dfTimewolf, which also has Turbinia as a dependency.   The bug referenced above gets tickled when both of these libraries are installed at the same time (because the Datastore package doesn't correctly limit the minimum versions of its dependencies, an incompatible version gets installed).
> Pin Datastore to work around upstream bug

- tools/gcf_init/deploy_gcf.py
- turbinia/client.py
- turbinia/config/__init__.py
- turbinia/config/turbinia_config.py
- turbinia/config/turbinia_config_test.py
- turbinia/evidence.py
- turbinia/output_manager.py
- turbinia/processors/google_cloud.py
- turbinia/pubsub.py
- turbinia/state_manager.py
- turbinia/task_manager.py
- turbinia/turbiniactl.py
This PR does the following:
- Makes `None` a valid value for some optional configuration variables
- Renames some configuration vars to be more consistent
- Makes some of the config var comparisons case insensitive
- Updates the config file and text
> Make some config vars optional

- setup.py
Redis had a major version bump (to 3.x) yesterday and I spent a while scratching my head trying to figure out why some datastore things I didn't touch had broken 😄 
This pins the major version of each lib, while allowing newer minor versions.
> Pin Celery/Kombu/Redis major versions

- requirements.txt
Current pypi version of google-cloud-storage (1.13.0) requires google-cloud-core 0.28.1 (before the rename of google.cloud.iam (core) to google.api_core.iam) while the latest version on pypi is 0.29
> Fix version of google-cloud-core

- turbinia/output_manager.py
- turbinia/output_manager_test.py
See #304 for details, but after #282, Tasks that held evidence in the tmp_dir saved the temp path instead of the locally saved path (thereby breaking when different Tasks processed the newly created Evidence).  This fixes that.
FYI @ericzinnikas , LMK what you think.
> Update Evidence local_path when it's saved

- setup.py
Python Redis module v3 is released. There are some breaking changes, but luckily they don't affect our implementation.
Local testing completed successfully.
> Update redis to 3.0

- turbinia/celery.py
- turbinia/client.py
- If something weird happens when pulling items off of the queue, log it and continue.
- Turns out we cannot use `pool=solo`. This forces Celery to be single threaded and even disables the heartbeat (which is required for the server to know workers are alive)... so any task which takes longer than the heartbeat timeout to process will be duplicated. Solution for this coming in a following PR.
> Celery: Handle unusual queue exceptions; disable 'pool=solo'

- turbinia/workers/__init__.py
Issue #331
Added a log_files parameter to TurbiniaTask.execute() that always saves even if the execution fails.
> Added log_files parameter to TurbiniaTask.execute()

- turbinia/workers/__init__.py
- turbinia/workers/grep.py
Also adds success_codes parameter to TurbiniaTask.execute() to allow specification of multiple acceptable return codes for a "successful" status.
> Fix grep status

- turbinia/jobs/http_access_logs.py
I had fixed this a while back in the release branch, but I guess I forgot to push this to master.
Tests should be fixed after https://github.com/google/turbinia/pull/353 is in.
> Fix updated Docker artifact name

- tools/gcf_init/deploy_gcf.py
- `--runtime` is now required
- `gcloud functions` is no longer in beta
- datastore index creation syntax changed as well
> Update GCF deploy for new gcloud options

- turbinia/state_manager.py
Addresses #371 
We were checking the `TASK_MANAGER` setting when we should probably have been looking at the `STATE_MANAGER` setting (as we do later on around line 60).
> Check proper config for state manager

- turbinia/evidence.py
... otherwise deserialization fails in [evidence_decode](https://github.com/google/turbinia/blob/master/turbinia/evidence.py#L60) when instantiating a new ExportedFileArtifact object with no parameters
> Set default value for artifact_name

- turbinia/turbiniactl.py
Log level is set to INFO or verbose by default.  This was overriding the debug flag, so I changed it to just fall through to the default intead.
> Fix debug flag

- turbinia/config/turbinia_config.py
- turbinia/output_manager.py
- turbinia/output_manager_test.py
The cloud storage modules were only loading if the task_manager was set to PSQ, but it should have been checking whether GCS was actually set in the config.  Also setting GCS_OUTPUT_PATH to default in the config so that it doesn't accidentally get loaded (otherwise we'd just see other errors later).
Fixes #375
> Load storage only when GCS is configured

- turbinia/output_manager.py
- turbinia/workers/__init__.py
This should prevent an empty file from ever getting saved, and should also give a better error message in case they do, or in case an empty file is passed in in the initial processing request from a user.  Also catch exceptions when copying to/from GCS.   This adds checks for empty files at the output_manager layer so that when this happens that a more sane exception/error is thrown/logged in case things fall through.  I'm also capturing this condition at the worker for the non-fatal cases.
> Check for empty files before saving

- turbinia/evidence.py
- turbinia/jobs/plaso.py
- turbinia/turbiniactl.py
- turbinia/workers/plaso.py
Tested locally with the following options
`turbiniactl apfs -l [DISK LOCATION] -p [PASSWORD]`
`turbiniactl apfs -l [DISK LOCATION] -r [RECOVERY KEY]`
Haven't had much chance to work on #346 yet, but this PR provides support for APFS Encrypted disk to be processed by Plaso in the meantime (similar to #349 ).
> Add Encrypted APFS support for Plaso

- tools/gcf_init/index.js
- tools/gcf_init/index.yaml
- turbinia/client.py
- turbinia/client_test.py
- turbinia/message.py
- turbinia/task_manager.py
- turbinia/turbiniactl.py
- turbinia/workers/__init__.py
This makes it so that `turbiniactl status -u user` actually works to query for all Tasks for that user.  Previously the user was being set server-side, so it wasn't actually setting the original requester.
This also changes most of the code/storage references from 'user' to 'requester' to be a little clearer in the code what is being referenced (because in some of the Google Cloud Functions both are used).
>  Fix setting and querying for user/requester

- turbinia/jobs/jenkins.py
- turbinia/lib/utils.py
- turbinia/workers/analysis/jenkins.py
- turbinia/workers/analysis/jenkins_test.py
This fixes the jenkins analysis task, but at the cost of running it much more inefficiently.  This extracts all config.xml files and then post filters them to only analyze the files with an interesting path because the Plaso and Forensic Artifacts path filters/regexes are not very flexible.  This means that image_export.py has to iterate through every file on disk because it's only validating the filename and not the path.   It also refactors image_export into it's own method so we can run it independently of extract_artifacts(), and updates the report a bit.
> Fix jenkins analysis task

- turbinia/workers/volatility.py
`vol2` -> `vol.py`
Volatility's `setup.py` [defines it as the latter](https://github.com/volatilityfoundation/volatility/blob/master/setup.py#L59), so I think we should make it match.
FYI @mwatkins-fb
> Change Volatility binary name

- README.md
The link for the documentation for developing new tasks was pointing to the how it works documentation.
> Fix new tasks doc link

- turbinia/lib/libcloudforensics.py
plaso-tools will install python3-plaso, so unless python-plaso is explicitly needed it does not need to be included in the package list
> Added libfsapfs-tools and removed python-plaso from libcloudforensics

- turbinia/evidence.py
- turbinia/evidence_test.py
- turbinia/workers/__init__.py
- turbinia/workers/workers_test.py
This validation happens on the worker instead of on the server so that the errors will still bubble up to the user.  By default this will just check that the attributes listed in the REQUIRED_ATTRIBUTES for the given evidence type are set, but each evidence object can potentially override this method to implement their own more stringent checks as required.
> Add basic evidence validation

- turbinia/client.py
- turbinia/client_test.py
- turbinia/config/__init__.py
- turbinia/state_manager.py
- turbinia/turbiniactl.py
- turbinia/workers/__init__.py
- Adds run_time attribute of Task to be stored in Datastore/Redis
- Also convert all date formatting to use same format
- Also deserializes date output from datastore/redis
Regular stats output looks like:
```
Execution time statistics for Turbinia:
All Tasks: Count: 13, Min: 0:00:00, Mean: 0:00:09, Max: 0:01:36
Successful Tasks: Count: 10, Min: 0:00:01, Mean: 0:00:10, Max: 0:01:36
Failed Tasks: Count: 3, Min: 0:00:00, Mean: 0:00:00, Max: 0:00:08
Total Request Time: Count: 1, Min: 0:02:54, Mean: 0:02:54, Max: 0:02:54
Task type FileArtifactExtractionTask: Count: 5, Min: 0:00:09, Mean: 0:00:09, Max: 0:00:10
Task type GrepTask: Count: 2, Min: 0:00:00, Mean: 0:00:00, Max: 0:00:00
Task type HadoopAnalysisTask: Count: 1, Min: 0:00:10, Mean: 0:00:10, Max: 0:00:10
Task type JenkinsAnalysisTask: …
```
> Generate basic task execution time statistics

- turbinia/config/__init__.py
- turbinia/config/logger.py
This cleans up the following annoying warnings:
[WARNING] No project ID could be determined. Consider running `gcloud config set project` or setting the GOOGLE_CLOUD_PROJECT environment variable
UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
> Remove warnings and set project explicitly

- turbinia/evidence.py
- turbinia/output_manager.py
- turbinia/output_manager_test.py
For evidence objects with `save_metadata` set, this will write a `.metadata.json` file with all of the evidence context written to it.
> Add saving of metadata.json files to output manager

- turbinia/workers/bulk_extractor.py
- turbinia/workers/bulk_extractor_test.py
Added a method in the bulk extractor worker that will check for the existence of a given xml value before trying to grab it's text. This prevents the whole report from failing in the event there is a missing field in the report.
> Method to check for xml attribs for report generation in bulk extractor worker

- turbinia/output_manager.py
- turbinia/workers/__init__.py
We still want to run the file copying when using a shared filesystem because we use it to copy from tmp files to the main shared filesystem.    We also want to save the result even if the file doesn't get copied.   This also updates some comments to be more clear.
> Fix saving files on local instances

- turbinia/evidence.py
The exception would be thrown each time the PsortJob is run and it has to do with the PlasoCsvFile method being inherited from PlasoFile evidence type and the super() method get's called twice. I haven't noticed a need for the PlasoCsvFile to be inherited so I changed it to inherit from the base Evidence class. Exception that was being thrown:
```
[ERROR] PsortTask Task failed with exception: [__init__() got multiple values for keyword argument 'copyable']
[INFO] Traceback (most recent call last):
File "turbinia/turbinia/workers/__init__.py", line 619, in run_wrapper
self.result = self.run(evidence, self.result)
File "turbinia/turbinia/workers/psort.py", line 42, in run
psort_evidence = PlasoCsvFile(source_path=psort_file)
File "turbinia/turbinia/evidence.py", line 549, in __init__ …
```
> Fixed exception thrown during evidence creation of PsortJob

- turbinia/client.py
- turbinia/client_test.py
- turbinia/config/__init__.py
- turbinia/config/turbinia_config_tmpl.py
- turbinia/jobs/manager.py
- turbinia/task_manager.py
- turbinia/turbiniactl.py
- turbinia/workers/__init__.py
- turbinia/workers/workers_test.py
Added functionality to filter jobs by worker via --jobs_whitelist or --jobs_blacklist flags or in the config file inside the DISABLE_JOBS variable. Updated the config to do a system dependency check prior to starting the worker (it will check if the job name in the dependency check matches the list of available jobs and then run a check for all the programs to see if they exist or not.). The task.run_wrapper will check if a given job is enabled in the worker before running and if it does not, will set the result.status warning the user that the job has been disabled on the worker.
> Added functionality to filter jobs and run a system dependency check on the worker. 

- setup.py
The internal API of pip changed and this is a workaround for #492 .  This seems to work just fine for `pip install -e .`, but I'm not actually sure what the session is for, and I saw other people setting it to other values as a workaround.   Longer term we'll have to come up with a different fix to not use parse_requirements at all.
> Remove pip session from setup

- turbinia/workers/plaso.py
This is a temporary mechanism to import Plaso artifacts/parsers/file_filters from the --recipe_config flag while #486 is being finalized, and once that's in place it will replace this. 
Tested with the following (since the Plaso flags are mutually exclusive):
`turbiniactl --jobs_whitelist PlasoJob -f --recipe_config='file_filters=/foo/bar:/bar/foo' rawdisk -l /tmp/test-small.img`
`turbiniactl --jobs_whitelist PlasoJob -f --recipe_config='artifact_filters=BrowserCache:BrowserHistory,parsers=webhist:linux' rawdisk -l /tmp/test-small.img`
> Get artifacts/parsers/file_filter from --recipe_config

- turbinia/workers/__init__.py
Fixes #498  by running the serialization check against the serialized version of the result (instead of the result).  I also changed the serialization method to be safe to run multiple times by returning a copy.
> Fix TurbiniaTaskResult serialization

- turbinia/turbiniactl.py
- turbinia/workers/plaso.py
Removes the  `--vss_stores all` flag from the default run of the Plaso Task, but this can now be passed in with `--recipe_config='vss=all'` if needed.  Also fixes format string in turbiniactl --recipe_config parsing.
> Remove --vss_stores all from default Plaso Task

- turbinia/output_manager.py
- turbinia/output_manager_test.py
This is so we don't have to infer the path from the metadata file location and name, and the Timesketch GCS importer can read it from the json file.
> Add evidence path to metadata file

- README.md
- docs/using-docker.md
- turbinia/client.py
Updated documentation for Docker usage instructions and fixed a part of the Docker dependency check where the python Docker library pulls only the first 10 characters of the Image id and running a command such as docker image ls, will pull the image id containing the first 12 characters.
> Updated documentation for Docker usage instructions and fixed docker dependency check to check image id length

- .style.yapf
Per: https://github.com/google/yapf/commit/22ef70f3c497436adf59934b2ffa84ce6f962b88 variable for 'chromium' style guide was updated to 'yapf'
> Fixed yapf style update from 'chromium' to 'yapf'

- turbinia/workers/sshd.py
Since we are encoding the data into utf-8, the data type is bytes so we have to open the file with 'wb' instead of 'w'
> Fixed write/encoding issue with SSHD task writing to output file

- turbinia/yapf_test.py
Fixed yapf encoding issue when running tests. Issue was due to Python3 automatic encoding so had to decode the value instead.
> Fixed yapf encoding issue

- turbinia/turbiniactl.py
Currently the Turbinia client will copy the disk from the source zone/project when the project is different, but this will make it so that it will copy the disk even when the project is the same but the zone is different.
> Copy disks when only zone is different

- turbinia/processors/archive.py
- turbinia/turbiniactl.py
* If a directory is passed by the `turbinia client`, adds logic to check within the config if it is a `SHARED_FILESYSTEM` and if NOT, convert the `Directory` evidence type into a `CompressedDirectory` evidence type.
> Auto conversion of Directory evidence to CompressedDirectory

- turbinia/client.py
function check_system_dependencies expects to be given a dict. The constructor on TurbiniaCeleryWorker feeds the unprocessed list from the config module, prompting an AttributeError triggered by Items() being called on a list.
Fixed by feeding the dictionary resulting from ParseDependencies, as happens in the TurbiniaPsqWorker constructor.
> small fix on dependency checker for local turbinia

- turbinia/state_manager.py
potential minor bug in RedisStateManager. The UpdateTask function gets a dictionary of task attributes from the get_task_dict function, it then attempts to replace the value associated to the 'run_time' key to a second count. This is something that the get_task_dict already does. Therefore the total_seconds method is called on a float object causing a AttributeError.
> minor fix on redis state manager

- turbinia/evidence.py
- turbinia/evidence_test.py
- turbinia/jobs/photorec.py
- turbinia/output_manager.py
- turbinia/processors/archive.py
- turbinia/task_manager_test.py
- turbinia/workers/__init__.py
- turbinia/workers/analysis/jenkins.py
- turbinia/workers/analysis/jupyter.py
- turbinia/workers/analysis/wordpress.py
- turbinia/workers/artifact.py
- turbinia/workers/bulk_extractor.py
- turbinia/workers/docker.py
- turbinia/workers/hadoop.py
- turbinia/workers/photorec.py
- turbinia/workers/plaso.py
- turbinia/workers/redis.py
- turbinia/workers/strings.py
- turbinia/workers/workers_test.py
This allows pre-processing to only be run when it is needed.  This eliminates a lot of extra work done by the workers, but also makes setup a lot more graceful, and errors cause fewer resources to be left around.
Copying some relevant bits from the docstrings for `Evidence.preprocess()`, see there for more info:
Tasks export a list of the required_states they have for the state of the
Evidence it can process in `TurbiniaTask.REQUIRED_STATES`[1].  Evidence also
exports a list of the possible states it can have after pre/post-processing
in `Evidence.POSSIBLE_STATES`.  The pre-processors should run selectively
based on the these requirements that come from the Task, and the
post-processors should run selectively based on the current state of the
Evidence.
If a Task requires a given state …
> Allow optional preprocessing

- docker/server/start.sh
- docker/worker/start.sh
The current docker image for both server and worker uses hard coded paths for log files and output. This PR changes that and will let Turbinia pick those from the config file instead.
> Use config settings for log and output dirs

- turbinia/e2e/googleclouddisk.sh
- turbinia/e2e/teardown-gce.sh
* IAM roles and service account are cleaned up when test is done
* debug flag is set for each turbiniactl command
* e2e return value parsing improvements
* include GCS stored output of each task in local archive (excluding StringAsciiTask on whole disk due to size)
> Some googleclouddisk e2e test improvements

- docker/server/start.sh
- docker/worker/start.sh
To support custom location of the logfile, e.g. when having  a multinode setup using docker compose there need to be a separate logfile for each node. This PR adds support for that via a env variable.
This variable can be set per node using the docker compose file with the --env TURBINIA_LOG_FILE=/foo/bar.log
> Support logfile path from env variable

- .github/workflows/actions.yml
The following PR creates an `actions.yml` file that will replicate the test run of Travis by installing Turbinia dependencies then running ./run_tests.py. Fixes #611
> PR to migrate Travis to Github actions

- turbinia/celery.py
- turbinia/client.py
- turbinia/evidence.py
- turbinia/jobs/interface.py
- turbinia/jobs/manager.py
- turbinia/lib/docker_manager.py
- turbinia/lib/dockermanager_test.py
- turbinia/message.py
- turbinia/output_manager.py
- turbinia/pubsub_test.py
- turbinia/state_manager.py
- turbinia/task_manager.py
- turbinia/workers/__init__.py
This Pull Request removes the implicit `object` inheritance from the Base Class. 
The Issue seems to be very minor but it improves the readability of the Code and since Python 3 inserts it for us behind the scenes, I suggested that its best remove them up.
> Removing useless Object inheritance

- turbinia/e2e/setup-gce.sh
To setup different version of the e2e tests (eg against dev docker images) we should be able to provide arbitrary switches to the terraform deploy.sh script.
> Add option to provide arbitrary arguments to deploy.sh

- turbinia/e2e/setup-gce.sh
As we now pass extra arguments to Terraform deploy.sh we should allow >1 argument instead of checking for exactly 1 argument.
> Allow >1 argument to setup-gce.sh

- turbinia/workers/binary_extractor.py
Allows you to specify something like `turbiniactl -C 'binary_extraction_path=%%users.homedir%%/Downloads/**'` (in ForensicsArtifacts format) to collect arbitrary files in an image with the binary extractor job.
> Custom artifact extraction recipe flag

- requirements.txt
- turbinia/client.py
2 small fixes so we can get the local stack to work again.
* add celery and redis to the requirements.txt (these are small and adding them there will make sure docker builds are consistent and work on both cloud and local)
* fix startup of celery worker ('celery' parameter is not needed anymore)
> Fix Turbinia local stack

- requirements.txt
The newest celery (5.x) is not compatible with our use of vines and kombu. Pinning to <5.0.
> Pin celery to <5.0

- requirements.txt
Dependency failure while building, solve by pinning PyJWT[crypto]<2
> Pin PyJWT.

- turbinia/client.py
When showing the 'running' tasks, the task runtime was showing as a negative value because the worker updated the time based on UTC and the client was using local time, and it looked like the task had finished in the future :).
> Fix worker runtime in status output

- setup.py
- turbinia/__init__.py
Add automatic release versioning using setuptools_scm.
Fixes #694 
```
$ turbiniactl -V
20190819.4.dev118+g9ca7def.d20210128
```
Using setuptools_scm where:
20190819 = tag (of master in this case)
.4 = version number of tag
.dev118 = the distance to this tag (e.g. number of revisions since latest tag)
+short commit hash
+build date
```
> Add dynamic release versioning.

- docker/worker/Dockerfile
- turbinia/lib/utils.py
- turbinia/processors/docker.py
- turbinia/processors/mount_local.py
- turbinia/processors/mount_local_test.py
- turbinia/workers/docker.py
Because we install de.py with pip, when we run it with `sudo` it can't find the path so we grab it before execution.   Also switch to using fsstat instead of lsblk because sometimes lsblk doesn't give output for common filesystems (even ext4).
> Use absolute path for dockerexplorer

- turbinia/workers/partitions.py
Prevents `UnboundLocalError: local variable 'path_specs' referenced before assignment` error in case of an exception during processing.
> Set path_spec by default

- requirements.txt
The imports for v2 have changed, so we either need to pin this >=2.0 or adjust the imports (and choosing to do the former here).
> Pin cloud logging to <2.1,>=2.0.0

- .devcontainer/devcontainer.json
To support loop devices we need to start the vscode devcontainer in privileged mode.
> Start devcontainer in privileged mode

- turbinia/workers/__init__.py
- turbinia/workers/workers_test.py
This way we can always get access to the stdout/stderr easily from saved output, and it's not dependent on how logs are saved from the Worker.  This also makes it easier for saving stdout as directly as Evidence output.
Also unset input evidence when serializing `TurbiniaTaskResults` which fixes: #779.
This should be submitted before #770
> Always save stdout/stderr from Task execution

- turbinia/workers/plaso.py
Fixes #801 .  Sets the unattended flag and also sets `--vss_stores` to `none` by default.
> Update Plaso flags

- turbinia/workers/docker.py
GetContainers() can return None which is a non-itterable object, this XS PR takes that into account.
> Handle None return value from GetContainers()

- turbinia/client.py
- turbinia/config/__init__.py
- turbinia/config/turbinia_config_test.py
- turbinia/config/turbinia_config_tmpl.py
- turbinia/jobs/interface.py
- turbinia/jobs/manager.py
- turbinia/lib/docker_manager.py
- turbinia/lib/dockermanager_test.py
- turbinia/workers/__init__.py
- turbinia/workers/plaso.py
Adds a timeout for each of the jobs that is configurable via turbiniarc. For any Job the worker runs that exceeds X amount of specified time, it'll raise a timeout exception and the job will report as failed.
> Heartbeat check for long running tasks

- turbinia/e2e/googleclouddisk.sh
Current e2e output size is 300MB for each run where most of the files included (eg BulkExtractor) are not needed. To limit size of the output file we exclude different result types.
> Exclude big files from test result output tgz.

- turbinia/client.py
The prometheus endpoint was only enabled in the server and psq-worker, let's add this to the celery-worker as well.
> Add prometheus endpoint to celery worker

- turbinia/client.py
This will append the count for each running/completed task name instead of duplicating the task names which makes the output of `turbiniactl status` a lot easier to read with high task counts while the task processing is still in progress.
Output format is `Tasks completed (3/4): [GrepTask:1, PlasoTask:1, PsortTask:1], waiting for [FinalizeRequestTask:1]`
> Show task name counts

- turbinia/workers/__init__.py
- turbinia/workers/plaso.py
The attribute misnaming caused the pre-processors not to attach the disk.  For the version mismatch, the error wasn't showing up as a failed task without explicitly setting the successful attribute.
> Fix PlasoTask attributes and version mismatch error

- turbinia/workers/analysis/linux_acct.py
Since this uses `image_export.py` we don't actually need the `MOUNTED` state after evidence pre-processing.   We do want the `DECOMPRESSED` state though for the `CompressedDirectory` evidence type.
> Update linux accounting Task required states

- docker/server/Dockerfile
- docker/worker/Dockerfile
Fixed permissions issues for start.sh when building docker image then when attempting to run, getting a permission denied. The root cause likely due to the `start.sh` file that was cloned before building having a different set of permissions when copied over to docker image.
> fixed permission issues for start.sh

- requirements.txt
- turbinia/jobs/binary_extractor.py
- turbinia/jobs/hadoop.py
- turbinia/jobs/http_access_logs.py
- turbinia/jobs/jenkins.py
- turbinia/jobs/jupyter.py
- turbinia/jobs/redis.py
- turbinia/jobs/sshd.py
- turbinia/jobs/tomcat.py
Switch analysis tasks to full disk evidence now that image_export runs unattended
> Switch analysis tasks to full disk evidence

- turbinia/jobs/manager.py
- turbinia/lib/utils.py
This also sets a default timeout value of 2hr for all tasks that don't have one set in the config.
> Add timeouts to image_export calls

- turbinia/evidence.py
And also make sure we pass in a task ID when we have stacked evidence types.
> Add resource_id to required attributes

- turbinia/evidence.py
- turbinia/evidence_test.py
- turbinia/workers/__init__.py
- turbinia/workers/workers_test.py
There was an issue with `postprocess` not removing the appropiate `task_id` when the Task is complete for the `parent_evidence`, this PR resolves that by not returning after doing the `PostProcessResourceState ` check and instead adds a `is_detachable` variable that equals True but evaluates to False if the `resource_id` is still in use and to not run the rest of the `postprocess` code. This PR also requires `task_id` be a required attribute of `postprocess` and `preprocess`
> Fixes for postprocess resource tracking

- turbinia/lib/recipe_helpers.py
This is used so that we can write the sketch_id to the metadata.json files so Timesketch knows what sketch to use.
> Add sketch_id to globals

- docker/local/local-config.sed
- docker/worker/Dockerfile
- requirements.txt
- turbinia/config/turbinia_config_tmpl.py
Fix a protobuf dependency that prevented the dev and experimental docker images from being build. Once the hindsight upstream code is fixed we can uncomment the installation again.
Fix #935
> Fix protobuf dependencies and comment out hindsight.

- turbinia/processors/resource_manager.py
- turbinia/processors/resource_manager_test.py
This PR adds in unit tests for `resource_manager.py` as well as updates the `resource_manager` to move closing out file handler close to finally statement in the event an exception is raised as well as returns `json_load` to remove the duplicate step in `PreProcessResourceState` and `PostProcessResourceState`.
> Added resource manager tests and update resource manager json load logic

- docs/user/install-gke.md
- k8s/gcp-pubsub/destroy-pubsub.sh
- k8s/gcp-pubsub/setup-pubsub.sh
- k8s/gcp-pubsub/turbinia-output-claim-filestore.yaml
- k8s/gcp-pubsub/turbinia-output-filestore.yaml
- k8s/gcp-pubsub/turbinia-server.yaml
- k8s/gcp-pubsub/turbinia-worker.yaml
- turbinia/config/__init__.py
- turbinia/config/turbinia_config_tmpl.py
The following PR deploys Filestore NFS share to Turbinia GKE to allow for persistent and shared storage.
* Added Deployment files `turbinia-output-claim-filestore.yaml` and `turbinia-output-filestore.yaml` which configure Filestore to the Kubernetes cluster
* Updated `setup-pubsub.sh` and `destroy-pubsub.sh` to create and destroy the Filestore Deployment files.
* Added a new config variable `LOG_DIR` to the `.turbiniarc` config template which sets the default output directory for logs.
* Updated `install-gke.md` docs with instructions for properly configuring Filestore.
> Persistent storage through Filestore 

- turbinia/workers/__init__.py
- turbinia/workers/workers_test.py
Changes the worker not to return generated Evidence files that point to source_paths that are empty.  Not all evidence has a source_path though, so source_path=None is still returned.
> Check for empty evidence

- turbinia/workers/__init__.py
- turbinia/workers/workers_test.py
* Fixes #945 
* Kills subprocess on timeout which should fix the subprocess retaining file handles to devices that cause post-processing failures
* Also save potential partial stdin/stdout when timeouts occur.
> Fix execution hangs and save output

- turbinia/config/turbinia_config_tmpl.py
- turbinia/evidence.py
- turbinia/processors/mount_local.py
- turbinia/processors/mount_local_test.py
Added evidence size to evidence objects for metrics tracking
- Currently only populating for RawDisk
@aarontp @wajihyassine - as discussed
> Add evidence size to evidence object

- turbinia/task_manager.py
- turbinia/workers/__init__.py
- turbinia/workers/workers_test.py
The `TurbiniaTaskResult.successful` status was not getting updated properly upon early failures which meant that the client thought the Task was continuing to run in this case.  Calling `close()` on the result will make sure that the worker log gets saved as well.
Also adding a server side check for this condition which forcefully sets `successful=False` which allows us to recover in case there are other times where the results aren't closed properly.
> Close results on early task setup failures

- turbinia/turbiniactl.py
googleclouddisk evidence type fails to initiate as two args are not in its namespace. This PR fixes that.
> Google cloud bulk processing bug fix

- docs/user/install-gke.md
- k8s/gcp-pubsub/turbinia-server.yaml
- k8s/gcp-pubsub/turbinia-worker.yaml
- turbinia/config/__init__.py
- turbinia/config/logger.py
- turbinia/config/turbinia_config_tmpl.py
- turbinia/turbiniactl.py
This PR moves the Python code in the Turbinia config file used to determine the node name for the default logger file name. I 've updated `LOG_FILE` back to `LOG_DIR` to take in a log directory path and added a new logic to check if user specified log name was given and if not to create the log name based on `LOG_DIR` and the host name.
In addition, the node name has been exposed through the `turbinia-server.yaml` and `turbinia-worker.yaml` file and logic added to check for `NODE_NAME` and append to the log name if it exists. This way we can correlate node name with pod name and fixes #973
> Move log node name init out of config file to turbinia code and expose NODE_NAME in GKE setup to correlate pod and node name

- tools/gcf_init/index.js
- turbinia/client.py
- turbinia/state_manager.py
- turbinia/turbiniactl.py
Added a status command for group_id. By default it only returns the requests and number of successful/failed/running tasks associated with given group_id. Run with --full_report command for full details on each request.
Sample output:
```
python3 turbinia/turbiniactl.py status  -g 2c4393fdb8bb4c7bb6aa5fb1fa1bc1f1
2022-01-25 18:20:26 [INFO] Turbinia version: unknown
2022-01-25 18:20:27 [INFO] Disabling non-allowlisted jobs configured to be disabled in the config file: volatilityjob, dockercontainersenumerationjob, photorecjob
Request Id a43c7d9fb1ef4d1a90c394737d777cf6 with 1 successful, 6 failed, and 0 running tasks.
Request Id 77952f84a956441c9c1c8235245a0930 with 1 successful, 6 failed, and 0 running tasks.
Request Id 0ca16d5884d3435fbec8bbd4522b3233 with 1 successful, 6 failed, and 0 …
```
> Retrieve status for bulk requests

- dfvfs_requirements.txt
- requirements.txt
pyOpenSSL recently updated to require `cryptography>=35` which also requires a Rust compiler to build.  https://www.pyopenssl.org/en/stable/changelog.html#id1
Pinning requirement to keep the dev environment green for now and prior to the next release we can revisit all of our pinned dependencies.
> Pin pyOpenSSL

- requirements.txt
Fixes a new dependency conflict with error reporting per 
```
error: google-cloud-logging 3.0.0 is installed but google-cloud-logging<3.0.0dev,>=1.14.0 is required by {'google-cloud-error-reporting'}
```
> Logging fix

- turbinia/evidence.py
Partition evidence was causing evidence serialization errors due to the path_spec attribute.
Clearing the path_spec before serialization since the path_spec is not required outside of the worker.
> Clear partition path specs before evidence serialization

- turbinia/workers/file_system_timeline.py
dfVFS raises IOError exceptions if a file system entry cannot be read. This was causing the task to fail and return as soon as the exception was caught. 
This pull request proposes a fix to ensure that the exceptions are properly handled to allow the task to continue to the next file entry if the previous file entry could not be read.
> Properly handle case when a file entry cannot be read by dfVFS

- turbinia/evidence.py
- turbinia/workers/fsstat.py
- turbinia/workers/fsstat_test.py
- turbinia/workers/partitions.py
> fsstat: fix for evidence object with 'None' path_spec

- turbinia/task_manager.py
- turbinia/workers/__init__.py
- turbinia/workers/workers_test.py
Sets the maximum size that the report can be before truncating it.  This is a best effort estimate and not a guarantee and comes from the limit for datastore entities[1] less some overhead for the rest of the attributes that will be saved in the response.
This also removes the stdout from the response object because this can also cause the size to grow too large and it is saved as a file anyway if we need it.
Fixes #1009
> Truncate large report text data

- turbinia/client.py
- turbinia/config/recipes/triage-linux.yaml
- turbinia/config/recipes/triage-macos.yml
- turbinia/config/recipes/triage-windows.yaml
- turbinia/config/recipes/triage.yaml
This PR removes PsortJob from the triage recipes and allows the Turbinia client to specify yara rules when loading an existing recipe file.
The reason to remove PosrtJob from the recipes is because other tools like Timesketch can read plaso format files directly so running psort is a bit redundant.
> Allow yara rules for existing recipes and remove PsortJob

- turbinia/task_manager.py
The Task stub doesn't seem to get set before the Task is actually returned from the worker but we can still grab the relevant data from the task object itself.
Fixes #1025
> Reference Task instead of Task stub

- turbinia/evidence.py
- turbinia/processors/partitions.py
- turbinia/workers/fsstat.py
- turbinia/workers/fsstat_test.py
- turbinia/workers/partitions.py
Fixing an error in populating dfVFS partition path_spec from location string.
In certain cases (particularly when an image was of a volume rather than full disk) the path_spec was not being populated during evidence preprocessing.
Fixes #1026
> Fix population of partition path_spec from location

- turbinia/client.py
This PR allows the turbinia client to accept yara rules while also loading a pre-defined recipe. It will include the yara rules in the loaded recipe's 'globals'
> Allow client to send yara rules along with recipe

- requirements.txt
Fixes #1040 
Pinning because google-cloud-storage was updated to require an incompatible google-cloud-core here:
https://github.com/googleapis/python-storage/pull/741/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7
> Pin google-cloud-storage

- turbinia/workers/artifact.py
Otherwise these Tasks won't be able to run on the mounted container and will get errors about `local_path` not being set.
Fixes #1037
> Add container mount state requirement to file extractions

- turbinia/config/logger.py
Add missing import in logger module
https://github.com/google/turbinia/blob/16c5862641f79ce3cf53a32d925d36cebc76ef98/turbinia/config/logger.py#L69
Fixes #1071
> Missing sys module import in logger.py

- turbinia/config/logger.py
What it says on the tin: The default stream logger goes to stderr, swapping to stdout.
> Change default logger to stdout from stderr

- k8s/gcp-pubsub/turbinia-server.yaml
- k8s/gcp-pubsub/turbinia-worker.yaml
- k8s/tools/.clusterconfig
- k8s/tools/cleanup-pubsub-gke.sh
- k8s/tools/deploy-pubsub-gke.sh
* Check whether dfDewey is deployed before trying to remove the Filestore
* Replace `--build-release-test` flag with `--build-experimental`
* Compute API is required to check VPC networks
* App Engine is required to create Datastore database
* Add Kubernetes service account and assign permissions used Workload Identity
* Kubernetes will now use this service account rather than the default compute service acccount
> Fixes for k8s scripts

- turbinia/workers/analysis/yara.py
- turbinia/workers/analysis/yara_test.py
Prepend the task_id to output files, since subsequent ones get clobbered by dftimewolf when pulling them down from GCS
> Unique names per Yara task

- turbinia/evidence.py
- turbinia/workers/psort.py
psort.py now retrieves the output_format to be able to output files with different extensions. One issue right now is that the value found in output_format is directly used as an extension (e.g. "--output-format dynamic" ends up as "xxx.dynamic"). It is possible to just change the extension as with the original implementation (just a .csv).
PlasoCsvFile can be renamed to cover all output formats, since it seems to work well with different outputs. If this is not wanted, a new class(es) can be made to cover the other output formats.
> Different extensions for output_format

- turbinia/processors/docker.py
This prevents some opaque errors in docker explorer.
> Check that docker directory exists before mounting

- turbinia/e2e/e2e-local.sh
- turbinia/e2e/e2e-recipe.yaml
- turbinia/evidence.py
- turbinia/workers/partitions.py
- turbinia/workers/partitions_test.py
* Filtering partitions processed by default based on filesystem and size
* Adding task config options to control which partitions are processed
Fixes: #729
> Filter Partitions Processed by Default

- turbinia/workers/__init__.py
- turbinia/workers/workers_test.py
Switching to string for all stdout and sterr values, such that the file handlers can be set to string as well.
For more detail see #1121
> Standardizing stdout and sterr for docker and system executions

- turbinia/workers/file_system_timeline.py
It seems that the dfVFS `FileEntry` objects are not being cleaned up and are holding on to the loopback device.
This is a temporary fix by manually deleting the `FileEntry` objects after processing each one. I'll do some more digging on the dfVFS side to see what's actually going on.
Relates to: #1124
> Temporary fix for releasing loopback devices

- requirements.txt
- turbinia/evidence.py
- turbinia/processors/mount_local.py
- turbinia/processors/mount_local_test.py
* To fix #1122  in addition to #1144 by @dfjxs, which fixes an issue with `FileSystemTimeline` and dfvfs keeping file handles on loop device.
* Adds filelock to PreprocessLosetup and PostprocessDeleteLosetup to prevent race condition of both these functions executing at the same time, causing it to seem like the output from `PostprocessDeleteLosetup` still has a device attached when another pod/Task uses the loop device as soon as it gets freed
* Change output.find method for checking for device status to instead use regex match search
* Added for loop in `PostprocessDeleteLosetup` to not fail on first device status check in case the device still needs a few more seconds to detach from the system
> Lofix race condition + device check fix

- k8s/celery/turbinia-api-server.yaml
- k8s/celery/turbinia-api-service.yaml
Adds k8s container for the Turbinia API server. Still need to figure out the oauth2 setup component at bootstrap + using turbiniamgmt cli, but adding this in as a first step which will spin up the API server and can be accessed locally within the cluster.
> Api k8s pod and service

- requirements.txt
Was getting the following error when building dependencies
```
error: protobuf 3.20.2 is installed but protobuf>=4.21.3 is required by {'grpcio-status'}
```
Due to new release in [grpcio-status](https://pypi.org/project/grpcio-status/#history). Pinning  grpcio-status<1.49.0,>=1.33.2 to fix issue
> grpcio-status / protobuf dep conflict pinning 

- docker/local/docker-compose.yml
Fixes permission issues with mounting turbinia config file into container and code being able to recognize it. Also since nothing else should be created in that path, makes it a little more secure.
> Fix Docker config file mapping

- docs/user/gke-sre.md
Fixes the broken link references after migrating k8s files to a common folder
> fix broken links in gke sre doc

- turbinia/config/rules/suspicious_cron.yar
Currently firing on `/usr/lib64/python3.6/site-packages/sos/report/plugins/__pycache__/cron.cpython-36*` files
> Tighten Cron rule to not match on legit Kubernetes

- docker/vscode/Dockerfile
This PR ensures the devcontainer builds using updated apt packages. I noticed the build can fail due to stale deb packages when rebuilding the container as it runs different apt install commands.
> Devcontainer: Run apt-update before installing packages

- turbinia/config/turbinia_config_tmpl.py
fix typo in turbinia api config causing allowed origins for local testing to not correctly be set
> fix typo in turbinia api config 

- docker/worker/Dockerfile
- turbinia/config/turbinia_config_tmpl.py
- turbinia/evidence.py
- turbinia/processors/mount_local.py
- turbinia/processors/mount_local_test.py
- turbinia/workers/partitions.py
Adding support for APFS via pre-processors.
APFS volumes can't be "attached", so we attach the containing partition, or the whole disk if there isn't a containing partition.
> Add APFS Support

- docker/worker/Dockerfile
Step in Worker Dockerfile seems to fail at random when pulling Yara repo from github. Re wrote slightly differently and seems like using `curl -L` allows it to be more reliable.
Failure we are seeing in Worker build:
```
wget: missing URL
Usage: wget [OPTION]... [URL]...
Try `wget --help' for more options.
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command '/bin/sh -c cd /opt/fraken/yara && curl -s https://api.github.com/repos/VirusTotal/Yara/releases/latest | sed -n 's/.*"tarball_url": "\(.*\)",.*/\1/p' | xargs -n1 wget -O - -q | tar -xz --strip-components=1     && ./bootstrap.sh     && ./configure     && make && sudo make install && sudo ldconfig' returned a non-zero code: 2
```
> Fix yara DL in dockerbuild

- turbinia/processors/mount_local.py
- turbinia/processors/mount_local_test.py
Fixes issue where two workers on same machine try to mount an XFS image causing an error with msg`Filesystem has duplicate UUID`, which has been the culprit to some failed Tasks we've been seeing from testing.
Adding in `-o nouuid` flag to ignore the UUID for XFS images when mounting, which in our case is fine as the UUID is not being used for anything in Turbinia.
> Fix for duplicate UUID issue in XFS image mounts

- docker/controller/Dockerfile
Moved RUN command to single command and chown to turbinia:turbinia so we don't have to edit/run with sudo
> Fix permission on loadtest scripts

- turbinia/api/cli/requirements.txt
Add ```google-auth-oauthlib``` to turbinia-client requirements for OAuth2 flows.
> Fix requirements

- turbinia/config/__init__.py
- turbinia/evidence.py
- turbinia/processors/google_cloud.py
- turbinia/processors/resource_manager.py
In response to this https://github.com/google/turbinia/issues/1249, adding following changes:
* Add more debug statements for evidence.preprocess and evidence.postprocess to more closely track each step.
* Move filelock in preprocess and postprocess to filelock any resource tracked evidence which essentially only allows for 1 attach or detach event, helped to further eliminate any race conditions between attaching and detaching a disk. 
* Add debug statement for resource manager to track resource state and add check to ensure intended resource state matches the resource state that was written (in the event with issues writing to the file).
* Sleep on attachDisk and detachDisk to allow time between API calls.
* Remove noisy debug statement with loading the config file
> Logging, filelock, sleep updates

- turbinia/lib/utils.py
Adding `--volumes` flag to `image_export.py` command. Without it, the worker would pause for user input on LVM (and other non-partition) volumes.
> Small fix for image_export.py

- turbinia/workers/plaso.py
Add the ```volumes``` option to both the PlasoParserTask and the PlasoHasherTask to make sure we parse all volumes (eg an image with multiple LVM volumes).
Fixes #1272
> Add volumes option to log2timeline command.

- .devcontainer/devcontainer.json
- requirements.txt
- turbinia/api/cli/setup.py
- turbinia/task_utils.py
Add a file lock for celery workers.
This would prevent GKE pods from being terminated by GKE when downscaling if a worker has an active task.
> Fix worker lock

- turbinia/api/cli/setup.py
- turbinia/api/cli/turbinia_client/helpers/auth_helper.py
- turbinia/api/models/request_status.py
Minor changes.
- Added ```google-auth-oauthlib``` to setup.py for turbinia-client.
- Bugfix for API server request status.
- Don't auto open a browser window when trying to perform OAuth2 flows (issues when running over ssh / console)
> Minor updates to auth_helper, turbinia-client and API server

- turbinia/api/cli/turbinia_client/helpers/formatter.py
Fix a bug causing the turbinia-client to raise an error when running ```status summary``` if there are no requests in Redis.
> Fix error when creating summary report

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/feature_request.yaml
- .github/PULL_REQUEST_TEMPLATE.md
Fixes #1307 
Adds:
* bug_report.yaml -> For filing bugs and by default adds "bug", "Needs triage" labels.
* feature_request.yaml -> For filing feature requests and by default adds "enhancement", "Needs triage" labels
* pull_request_template.md -> for submitting PRs
I was also considering breaking it down to more FR options for example one for Web UI, one for API/Celery, one for a new task, etc, but I feel like it will cause redundancy minus the added benefit of adding an extra label + descriptive title name.
At least this way if we add "Needs triage" then anyone reviewing the issue can update the labels after their review is done, but lmk if you prefer another way/if any other template will help!
> Add bug, FR, and PR request templates

- turbinia/api/cli/turbinia_client/helpers/formatter.py
Make f-string formatting more flexible as some values may be ```None``` when the formatter methods are invoked.
- fixes #1306
> Updates to turbinia-client formatter

- docker/worker/Dockerfile
Remove the command to pull the GIFT PPA key manually in the worker Dockerfile. add-apt-repository handles this for us.
> Remove curl gpg key command for GIFT PPA worker Docker build

- docker/worker/Dockerfile
- turbinia/tcelery.py
Update worker to be Celery >6.0 compatible by setting broker_connection_retry_on_startup to True
```
turbinia-worker        | [2023-07-27 15:51:02,971: WARNING/MainProcess] /usr/local/lib/python3.10/dist-packages/celery/worker/consumer/consumer.py:498: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
turbinia-worker        | whether broker connection retries are made during startup in Celery 6.0 and above.
turbinia-worker        | If you wish to retain the existing behavior for retrying connections on startup,
turbinia-worker        | you should set broker_connection_retry_on_startup to True.
```
> Update worker to be Celery >6.0 compatible

- turbinia/api/models/request_status.py
These changes will fix the web API, so that the evidence name appears in the table with the requests. This was broken as the 'start_time' attribute is not saved on Redis, but is now fixed as 'last_updated' is.
> Fixed problem with evidence name on Web API

- turbinia/evidence.py
- turbinia/processors/mount_local.py
- turbinia/workers/__init__.py
This PR implements the ```validate``` method for PlasoFile evidence objects. Validation will fail if the Plaso file contains no events. Validation is done by invoking ```pinfo.py``` which should be available in Turbinia workers.
This change will avoid the inclusion of Plaso files with no events to tasks ```saved_paths``` and will not be added to the task results, so further processing will not happen for Plaso output files with no events.
I also included some small changes to logging and returning an integer size in mount_local.py
- fixes #1327
> Validate newly created evidence output files after processing

- docker/server/Dockerfile
- docker/worker/Dockerfile
Optimize Turbinia worker docker image and bring size down with 32%. From 1.15 GB to 780MB.
* Bundle RUN requests including apt cleanup
* Disable pip caching
* Refactor out fraken build in different multi-stage build with latest golang to minimize vulnerability alerts
* Cleanup several git pulled folders
* remove apt installed libs not needed anymore due to above optimizations
* add more extensive comments and restructure RUN blocks more logically
Some smaller Turbinia server docker image updates.
Turbinia worker docker image was large.
> Optimize Turbinia worker and server docker image.

- turbinia/api/cli/turbinia_client/core/commands.py
- turbinia/api/cli/turbinia_client/helpers/formatter.py
The task markdown report in turbinia-client was reformatted to only show essential information for low-priority tasks. A new option, show_all (-a), has been added to the command to show all fields, regardless of priority. This change will also affect the tasks in the requests markdown report. Additionally, the requests report has been reformatted to order tasks by priority.
This is what the new `turbinia-client status request` output looks like:
> Reformatted the TaskMarkdownReport and the RequestMarkdownReport

- docker/worker/Dockerfile
- turbinia/lib/utils.py
- turbinia/workers/analysis/jenkins.py
- turbinia/workers/analysis/postgresql_acct_test.py
* Double Jenkins password cracking timeout due to 10 round bcrypt 
* Expand Jenkins regex to  handle nested dirs before the config.xml file
* Change password cracking heuristics to try the plain wordlist and then each word duplicated.  This fits into our timeout and still gives good results.
- fixes #1344
> Modify password cracking

- tools/fraken/Dockerfile
- tools/fraken/README.md
- tools/fraken/cloudbuild.yaml
Create a docker build file for Fraken (including cloud build configuration).
This will allow us:
* to run fraken standalone from a docker image
* to improve build simplicity and build speed for the worker (by copying in Fraken from existing image)
> Add Fraken docker build file

- turbinia/evidence.py
Updates the name attribute for GoogleCloudDisk evidence objects.
- fixes #1367
> Update googleclouddisk name

- turbinia/evidence.py
- turbinia/workers/analysis/jenkins.py
- turbinia/workers/analysis/jupyter.py
- turbinia/workers/analysis/linux_acct.py
- turbinia/workers/analysis/ssh_analyzer.py
- turbinia/workers/analysis/windows_acct.py
- turbinia/workers/analysis/wordpress_access.py
- turbinia/workers/analysis/wordpress_creds.py
- turbinia/workers/redis.py
- turbinia/workers/sshd.py
- turbinia/workers/tomcat.py
* Add some required states to a few Tasks.  Hoepfully this will fix the errors similar to `Task Foo requires Evidence to be in state Bar`.
* Make sure `path_specs` is defined and errors out properly when it's not set
* Some automatic editor changes for removing some trailing whitespace.
> Fix SSH Task and other required states

- turbinia/api/cli/turbinia_client/core/commands.py
- turbinia/api/cli/turbinia_client/core/groups.py
- turbinia/api/cli/turbinia_client/factory/factory.py
- turbinia/api/cli/turbinia_client/helpers/click_helper.py
- turbinia/api/cli/turbinia_client/turbiniacli.py
- turbinia/api/cli/turbinia_client/turbiniacli_tool.py
This PR adds a new "version" command to display the tool's version. It also implements changes to decouple API requests that retrieve evidence types to build the list of "submit" subcommands. This means that those API requests are only sent when running "submit" or one of its subcommands.
The ```create_request``` method was moved from the ```commands``` module to the ```click_helper``` module since it's not a command.
The evidence mapping API requests and ```CommandFactory``` methods that create dynamic click Commands are now invoked only when calling the ```submit``` command. Click can then "chain" the subcommands as they are generated during runtime.
- fixes #1213 
- fixes #1352
> Add version command and decouple evidence requests

- turbinia/api/cli/turbinia_client/core/commands.py
- turbinia/api/cli/turbinia_client/helpers/formatter.py
* Adds `--priority_filter` so we can dynamically change which priorities we want to see full report data for (similar to old `turbiniactl` implementation).  
* Further reduces the details of things with lower priority so only one line is shown for anything with a low priority
* Changes the default priority of details shown from "MEDIUM" to "HIGH"
* Changes `--show_all` from showing all details for all tasks no matter the priority to showing extra saved path fields for the tasks that are higher priority than the priority filter. 
* Sorts tasks by name in addition to priority and aggregates task summaries with the same exact task status
> Update report filtering

- turbinia/e2e/e2e-local.sh
Add check to e2e test to verify all containers come up.
- fixes #1388 
- [NA] Unit tests added.
- [NA] Documentation updated.
> Add check to e2e test to verify all containers come up.

- .devcontainer/devcontainer.json
- .github/workflows/e2e.yml
Speedup the e2e docker image builds. By changing the build tools from a simple docker build to using Buildkit in combination with Github Actions Caching there is a greater change of hitting the docker layer cache on subsequent builds for the docker images in the e2e test. 
See below link where the build times for api-server, server and worker were brought down to 29, 27 and 54 seconds.
https://github.com/hacktobeer/turbinia/actions/runs/6795148691/job/18472715886
Note: The cache hits are not guaranteed and depend on the changes made in the PR!
Github Actions Cache -> https://docs.docker.com/build/cache/backends/gha/
Buildkit -> https://docs.docker.com/build/buildkit/
- [NA] Unit tests added.
- [NA] Documentation updated.
> Speedup e2e docker image builds

- turbinia/api/cli/turbinia_client/core/commands.py
- turbinia/api/cli/turbinia_client/helpers/formatter.py
* Fixes unique task summary counts  so we can remove duplicate task outputs in the report to make it more succinct.
* Also sort request summary tasks output by last update time.
* Also set default priority filter for task status requests so all details are shown.
> Fix unique tasks and sort/filtering in report output

- k8s/tools/get-system-pods-list.py
- turbinia/evidence.py
- turbinia/workers/containerd.py
- turbinia/workers/containerd_test.py
Filters the output of ContainerEnumeration Task to remove any system containers and any containers with names or images that are known to be system related in order to reduce the Evidence/Task count noise with containers that we rarely will need to inspect.
Also:
* Has TASK_CONFIG vars for these filters so we can update them with a recipe
* Adds a  utility to list the namespaces and containers for a given cluster to make it easier to update this list in the future.
* Adds container evidence attributes for pod name and image name and includes them in the image name for readability
- fixes #1343
> Filter ContainerEnumeration output

- turbinia/api/cli/turbinia_client/core/commands.py
- turbinia/api/cli/turbinia_client/helpers/formatter.py
- turbinia/api/cli/turbinia_client/turbiniacli.py
- turbinia/api/cli/turbinia_client/turbiniacli_test.py
This PR update the methods used in API requests to use the ones that support the preload_content argument. It also adds a new response decoding method to handle cases where the API client does not deserialize the responses automatically, as is the case when preload_content in the requests is set to False.
- fixes #
> Update API calls in turbinia-client commands

- .github/workflows/actions.yml
Using cache and buildx can speedup the building of the docker images during the github actions.
None
> Use native cache and buildx for gihub tests action

- docker/vscode/Dockerfile
Anyone trying to use vscode devcontainer will run into issues with worker deps missing. Changing back to `turbinia-worker-dev` as thats working and is the most up to date
- [x ] All tests were successful.
> Change to turbinia-worker-dev as it has latest changes

- turbinia/notify_test.py
Adds unit tests for notify.py as it lacks any unit tests.
None
> Add unit tests for notify.py

- turbinia/e2e/run-e2e-gke.sh
Fixes an issue where port-forward connection wasn't able to establish after a first connection (happens very little and at random) so it retries the connection before considering the test failed
Also fixes request needing some time to populated on Turbinia server from when it was first submitted + minor nits.
> Add retry port-forward connection and logic to wait until request is populated

- turbinia/evidence.py
Make sure we only use the relevant json output of pinfo.py
- fixes #1417
> Add workaround for pinfo non-json warning output

- docs/user/using-docker.md
The documentation article "Using Docker for Job execution" was updated so it reflects the code in line 124 `turbinia/turbinia/lib /docker_manager.py`.
The changes update the documentation article *Using Docker for Job execution* so that it reflects the code in [docker_manager.py#L111](https://github.com/google/turbinia/blob/master/turbinia/lib/docker_manager.py#L111). 
The following errors occur when using the `IMAGE ID` instead of the `REPOSITORY` value:
```python3
2024-01-11 12:26:30 [WARNING] DOCKER_ENABLED=True is set in the config, but there is an error checking for the docker daemon: {0:s}
Traceback (most recent call last):
File "/home/turbinia/turbinia/worker.py", line 198, in __init__
check_docker_dependencies(dependencies)
File "/home/turbinia/turbinia/worker.py", line 91, in …
```
> Updated the "Using Docker for Job execution" documentation

- turbinia/tcelery.py
This is to disable implicit retries by Celery because it causes duplicate tasks that the task manager does not deal with appropriately when a task has timed out because the task stub has already been removed, which means that new Jobs do not get created based on the output evidence from the retried task.
- fixes #
> Remove Celery task_acks_late

- turbinia/config/turbinia_config_tmpl.py
list_file_entries.py still has the file extension in the latest version of Plaso (20240308).
> Update fs timeline dependency path

- turbinia/config/turbinia_config_tmpl.py
Revert #1475 which added the extension to match the worker build for the previous release, but this dependency has been updated in the latest build so needs to be added back.
- fixes #
> Add back list_file_entries file extension

- turbinia/worker_test.py
- turbinia/workers/__init__.py
- turbinia/workers/workers_test.py
Removes the registry setup for Prometheus as this causes the application metrics not to show up.  This also makes sure that we only initialize worker metrics once (otherwise we get duplicate timeseries errors from prometheus_client) and unregisters all metrics in worker task tearDown() instead of individual tests.
- [ x] All tests were successful.
> Remove Prometheus registry setup

- poetry.lock
- pyproject.toml
acstore latest non-stable release introduces changes that are incompatible with the latest Plaso release. Pinning to match GIFT PPA stable acstore release.
- fixes #
> Update acstore dependency version for Plaso

- web/src/App.vue
- web/src/components/RequestList.vue
> [web-ui] Only truncate long evidence names

- turbinia/workers/analysis/llm_analyzer.py
The LLM Analyser should fail nicely with non-UTF-8 input. Sometimes the artifact extractions yields non parseble input to the analyser. This PR catches that and logs it.
None
> LLMAnalyser UTF-8 decode input error

- turbinia/api/api_server_test.py
- turbinia/api/openapi.yaml
- turbinia/api/routes/config.py
- turbinia/api/utils.py
This PR adds a config.download API end point to download the Turbinia configuration file in it's original format.
- fixes #1514
> Add API server config.download functionality.

- turbinia/workers/__init__.py
- web/package-lock.json
- web/package.json
- web/src/App.vue
- web/src/components/RequestDetails.vue
- web/src/components/RequestList.vue
- web/src/components/TaskDetails.vue
- web/src/components/TaskList.vue
- web/src/utils/RestApiClient.js
- web/vite.config.js
* Fixes data table and text formatting causing overflow of text
* Added back multi-sort data table
* Expansion to the task id has now been moved to the right side next to the request id
* Request List table has been cleaned up and request ids are now clickable allowing you to see request details on the right
* Filter chips to filter by Task status (running or queued, successful, failed)
* Filter chip to include or exclude job names
* Task name is sorted by default
* Added `job_name` in `STORED_ATTRIBUTES` to expose it in the API used for filtering
* Dependency updates
> Web UI Filter Options and Table formatting fixes

- web/package-lock.json
- web/package.json
- web/src/components/RequestDetails.vue
- web/src/components/RequestReport.vue
- web/src/utils/RestApiClient.js
Adds a Request Report view which is enabled by clicking a `request_id` in the request list then clicking on the "View request report" button in the request details view.
Fixes #1280
> Web UI: Add request report view

- .vscode/settings.json
- turbinia/api/api_server_test.py
- turbinia/api/routes/request.py
- turbinia/api/routes/task.py
- web/package-lock.json
- web/src/components/RequestDetails.vue
- web/src/components/RequestReport.vue
- web/src/components/TaskDetails.vue
- web/src/utils/RestApiClient.js
This PR adds a new API endpoint to retrieve task reports in Markdown format.
It also includes related UI changes and minor path change for the ```/request/report``` endpoint that was added recently.
- fixes #1342
> New task report endpoint and UI changes

- turbinia/api/api_server_test.py
- turbinia/api/openapi.yaml
- turbinia/api/routes/download.py
- turbinia/api/routes/evidence.py
- turbinia/api/routes/router.py
Add an API endpoint to download a Turbinia output file `/api/download/output/{file_path}`.
> Add API endpoint download.output

- .vscode/launch.json
- docker/api_server/Dockerfile
- docs/developer/develop-minikube.md
- skaffold.yaml
- turbinia/api/api_server.py
- turbinia/debug.py
- turbinia/turbiniactl.py
Add API server configuration to skaffold so remote debugging of the API server container is possible and builds/deployments/file-syncing are managed by skaffold. 
None
None
> Add API server configuration to skaffold development config

- docs/developer/develop-minikube.md
- skaffold.yaml
- web/README.md
As the WebUI is build in Vue and we put a minified build in the API server it is not possible to debug this in the containers. This PR:
* adds a paragraph to the dev documentation on how to develop for the WebUI
* changes the skaffold config to prevent rebuilds of the api-server container when developing on the WebUI
* fixes the web README as `npm run serve` does not work as there is no `serve` profile.
- fixes #
> Add WebUI dev documentation and skaffold fix.

- test_data/turbinia_logs.log
- turbinia/api/api_server_test.py
- turbinia/api/openapi.yaml
- turbinia/api/routes/download.py
- turbinia/api/routes/evidence.py
- turbinia/api/routes/logs.py
- turbinia/api/routes/result.py
- turbinia/api/utils.py
- turbinia/config/logger.py
This PR creates new API endpoints to retrieve log data for Turbinia components in a similar way to the "tail" command.
It also adds a new endpoint to download evidence files based on evidence IDs.
- fixes #1528
> Added new API endpoints (logs, evidence)

- turbinia/api/client/README.md
- turbinia/api/client/docs/TurbiniaEvidenceApi.md
- turbinia/api/client/docs/TurbiniaLogsApi.md
- turbinia/api/client/docs/TurbiniaTasksApi.md
- turbinia/api/client/poetry.lock
- turbinia/api/client/pyproject.toml
- turbinia/api/client/turbinia_api_lib/api/turbinia_evidence_api.py
- turbinia/api/client/turbinia_api_lib/api/turbinia_logs_api.py
- turbinia/api/client/turbinia_api_lib/api/turbinia_tasks_api.py
Updated API library with latest endpoints using OpenAPI client generator.
- fixes #
> Update API library

- turbinia/api/cli/turbinia_client/core/commands.py
- turbinia/api/cli/turbinia_client/core/groups.py
- turbinia/api/cli/turbinia_client/turbiniacli_tool.py
This PR adds new commands to the turbinia cli tool.
- fixes #
> Update turbinia client with new logs commands

- turbinia/api/routes/logs.py
- turbinia/api/utils.py
Fix an issue with the tail helper method used by the API server to read log data.
- fixes #
> Refactor log tail method

- turbinia/config/__init__.py
- turbinia/config/turbinia_config_tmpl.py
- turbinia/task_manager.py
- turbinia/workers/__init__.py
- web/src/components/TaskList.vue
This PR adds logic to handle tasks that are revoked by Celery due to exceeding the task expiration time.
- fixes #1539
> Handle Celery tasks with REVOKED status

- docker/worker/cloudbuild.yaml
Adds the PPA_TRACK build argument to the Cloud Build configuration file to build Turbinia worker versions with software from different GIFT PPA tracks.
> Add ppa_track build arg to cloud build config

- docker/local/local-config.sed
- turbinia/api/cli/turbinia_client/core/groups.py
- turbinia/config/turbinia_config_tmpl.py
- turbinia/evidence.py
- turbinia/state_manager.py
- turbinia/task_manager.py
- turbinia/task_utils.py
- turbinia/tcelery.py
- turbinia/worker.py
- turbinia/workers/__init__.py
- turbinia/workers/dfdewey.py
- turbinia/workers/fsstat.py
- web/src/components/RequestDetails.vue
- web/src/components/RequestList.vue
- web/src/components/TaskDetails.vue
- web/src/components/TaskList.vue
This PR
- Fixes an issue in which task status is not properly tracked, which caused request status to never fully complete.
- Adds a ```result_backend``` configuration option for Celery in order to persist celery task metadata in Redis.
- Adds a ```worker_deduplicate_successful_tasks``` configuration option to Celery to avoid duplicate messages of successful tasks.
- Adds a ```task_reject_on_worker_lost``` configuration option to Celery so tasks can be re-queued if a worker abruptly exists (e.g. SIGTERM/SIGKILL signal sent from GKE or OS process to celery worker)
- Adds a ```celery_id``` attribute to Turbinia tasks for traceability between Turbinia and Celery tasks.
- Enables ```Celery mingle``` in the configuration to be able to handle revoked tasks between workers and worker clock …
> Various updates to task management

- turbinia/state_manager.py
- turbinia/task_manager.py
- turbinia/tcelery.py
- turbinia/workers/__init__.py
- turbinia/workers/workers_test.py
- web/src/components/TaskDetails.vue
- web/src/components/TaskList.vue
Refactor task status tracking in task_manager to utilize Celery state to determine actual task status.
- fixes #
> Task status v2

- turbinia/state_manager.py
- turbinia/task_manager.py
* Keep task results in the task manager when it's available so we don't overwrite the failure status message from the Tasks.
* Update a couple log lines
* Add a counter for failed tasks so we can compare worker view and server view of failed tasks.
> Keep task results if available and update logs/counter

- .vscode/launch.json
- docker/api_server/Dockerfile.dockerignore
- docker/local/docker-compose.yml
- docker/local/setup.sh
- docker/server/Dockerfile.dockerignore
- docker/worker/Dockerfile.dockerignore
Add local docker compose debugging settings and vscode launch configurations. This allows for local docker compose debugging of worker and server in vscode.
Extra:
- add local runtime folders to docker ignore files.
- add helper setup.sh to setup local docker compose folders.
None
> Add local docker compose debugging

- turbinia/workers/analysis/linux_acct.py
We assumed the password would always be `$6$` but we recently encountered `$1$` so let's let Hashcat autodetect
> Don't force password hash algo

- turbinia/lib/recipe_helpers.py
Fix default recipe path.
- fixes #
> Fix recipe path
